### ISSUE TITLE
Load dump

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#102]
0.6.20201229 почему-то не даёт ввести адрес больше 3800 в поле Start, а остальные поля не редактируются.
![image](https://user-images.githubusercontent.com/47472465/106464086-3a949a00-64a9-11eb-80a0-6fcdc32e81b4.png)

**Comment by samstyle** [comment]
Потому что у него длина C800, и чтобы не переваливать за FFFF, сделано ограничение

**Comment by ammehet** [comment]
У него длина 200 (#C8) байт. А вот это получается при попытке загрузить 512 (#200) байт:
![image](https://user-images.githubusercontent.com/47472465/106495327-96244f00-64cc-11eb-82b4-14911c203ec1.png)
Как-то некрасиво длина определяется.

**Comment by samstyle** [comment]
Ясно. Определяется правильно, неправильно вписывается в поле Lenght

**Comment by samstyle** [comment]
В последней сборке исправлено. Просьба проверить

**Comment by ammehet** [comment]
Да, теперь всё ок, спасибо!
