### ISSUE TITLE
Possible error ?

### ISSUE THREAD

**Issue by ZanyXDev** [samstyle/Xpeccy#105]
https://github.com/samstyle/Xpeccy/blob/56e66c7335f47df3c215b4856e843434bf2bc8bf/src/emulwin.cpp#L86

Why use `~Qt::WindowFullScreen`

**Comment by ped7g** [comment]
without checking Xpeccy source, this looks like "set window state to windowState() except full-screen), ie. this will either always reset to non-fullscreen, or not affect full-screen (depends on semantics of `setWindowState` how it deals with full screen bit set to zero.

**Comment by samstyle** [comment]
yep, this is 'reset fullscreen bit'
