### ISSUE TITLE
What is the minimum version of the project.

### ISSUE THREAD

**Issue by ZanyXDev** [samstyle/Xpeccy#111]
С++ 11 or less ?
Qt 5.15.2 or less ?
cmake 3.19.2 or less ?

**Comment by samstyle** [comment]
I have minimum on sandbox with suse13.1:
cmake 3.3.2
Qt 5.1.1
gcc/g++ 4.8.1
c++11 (i don't sure about this)
minimum required versions may be older

there is cmake option to build on Qt4 (-DQT4BUILD=1), but i did't build this version for a long time, so i don't sure about minimum Qt4 version (4.6, i think)

**Comment by ZanyXDev** [comment]
It may be time to drop QT4 support?

**Comment by ZanyXDev** [comment]
QT 5.1.1 released 8 year ago :( 
https://www.qt.io/blog/2013/08/28/qt-5-1-1-released
