### ISSUE TITLE
+2A reset

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#113]
Ресет +2A успешно отрабатывает примерно 4 раза из 10. Ромы стандартные от +3, версии 4.0 и 4.1 ведут себя одинаково.
Остальные спектрумы, включая +2 без A и +3(e) ведут себя корректно.
Началось это в 0.6.20201122, в 0.6.20201026 стабильно срабатывало.
Выглядит как мусор на экране и вис, либо вот такой вис:
![image](https://user-images.githubusercontent.com/47472465/110313375-64486000-8017-11eb-8d07-fcc23a4c60ca.png)

**Comment by samstyle** [comment]
Занятно. ПЗУ +2 пытается читать из портов +3dos-а (2ffd/3ffd), хотя по идее его там не должно быть. Случается конфликт портов (или тупо чтение из порта FF) и какие-то рандомные данные вместо ожидаемых.

**Comment by ammehet** [comment]
+2A как бы должен в +3DOS ходить, у него там рам-диск. И да, судя по описанию релиза, порт FF появился как раз в 0.6.20201122.

**Comment by ammehet** [comment]
В 0.6.20210326 стало стабильно, спасибо!
