### ISSUE TITLE
[linux] alt-tab делает активным главное окно, а не окно дебагера

### ISSUE THREAD

**Issue by lvd2** [samstyle/Xpeccy#114]
1. запустить xpeccy
2. нажать ESC шоб вылез дебагер
3. alt-tabом перекючиться на окна других процессов
4. им же переключиться на xpeccy
5. активным станет основное окно, а не окно дебагера, что не есть правильно и требует вести мышкой делать активным окно дебагера.

**Comment by samstyle** [comment]
побочный эффект от не-модальности окна дебагера. оставлю только для винды, потому что ради неё это и затевалось...
