### ISSUE TITLE
[MacOS] 0.6.20210326 дебаггер

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#115]
1)  Load dump, save dump и memory filler вешают всё, даже окошко с параметрами не показывается. При этом Save dump по хоткею работает, Load dump не работает.
2) измельчали шрифты в дизасме, полях ввода и выпадающих списках
![image](https://user-images.githubusercontent.com/47472465/112726127-d0d6c080-8f2c-11eb-936d-7e3792c14d36.png)

**Comment by samstyle** [comment]
Шрифты пойманы.
С окошками не совсем понял. Они показываются. MemFill, наверное, из-за своих свойств, вылезает из-под заголовка, но open dump/save dump вполне работают по хоткеям
![Screenshot_20210327_192742](https://user-images.githubusercontent.com/474306/112727254-c91a1a80-8f32-11eb-9fa6-9b37ef17e2e8.png)

**Comment by ammehet** [comment]
О, поменял хоткей Load dump на нестандартный от балды – заработало. По Ctrl+O не работает. А через мышку все трое не показываются и вешается всё до принудительного срубания.

Search тоже из-под заголовка вылазит, но работает и по хоткею, и мышой. А Memory fill нет.

**Comment by samstyle** [comment]
Всем под-окнам дебагера поменял модальность. Показываются, не вешают. Шрифты вроде выровнял, но в регистрах всё равно остались мелкие, пока непонятно...
dmg в релизе обновил
https://github.com/samstyle/Xpeccy/releases/download/0.6.20210327/xpeccy_0.6.20210327_x86_64.dmg

**Comment by ammehet** [comment]
Да, теперь они стали выезжать из-под заголовка, и вешаться перестало.
А если ui/debuger.ui строки 16 и 967 pointsize 9 на 13 поменять?

**Comment by samstyle** [comment]
> А если ui/debuger.ui строки 16 и 967 pointsize 9 на 13 поменять?

Я в QtDesigner всё делаю, он уже сам генерит ui. Было задание шрифта отдельно для дампа - убрал. Было задание шрифта для всего окна отладчика - убрал (по умолчанию размер 13), но регистры от этого не вылечились

**Comment by ammehet** [comment]
Модальность похоже починилась в 0.6.20210407, ZX Keyboard работает. Остался пропорциональный шрифт в дизасме (некритично) и в мемори дампе, там совсем некрасиво в правой части, где символьное представление
![Screen Shot 2021-04-08 at 20 00 24](https://user-images.githubusercontent.com/47472465/114067322-5d766c80-98a5-11eb-9dd7-2e1a01f2da7b.png)

**Comment by Volutar** [comment]
> в мемори дампе, там совсем некрасиво в правой части, где символьное представление
Оно так везде, не только в MacOS.

**Comment by ammehet** [comment]
Спасибо за шрифты! Для полного фен-шуя не хватает только символьного представления хексов на вкладке FDD. Было бы удобно видеть части разбросанного по трекам каталога +3DOS. Да и в TR-DOS это тоже было бы не лишним
![image](https://user-images.githubusercontent.com/47472465/122656723-0115b000-d166-11eb-9535-5631c446d4ff.png)
