### ISSUE TITLE
Pentagon timing

### ISSUE THREAD

**Issue by holub** [samstyle/Xpeccy#116]
Если судить по Across The Edge - Pentagon timing не совсем точный.
https://zxaaa.net/view_demo.php?id=9284

В ShockMD также бордюр эфект не точен: https://zxart.ee/eng/software/demoscene/demo/shock-megademo/

Это проблема множественных клонов Pentagon, или ошибки в эмуляции?

**Comment by samstyle** [comment]
Часто замечаю смещение бордюра налево на 1 точку. Почему - ума не приложу.
Что касательно именно пентагоновских таймингов, то там есть особеность в чтении пикселей/атрибутов. Как это сэмулировать, тоже пока не придумал.

**Comment by holub** [comment]
Там может смещенте быть на 1,2,3 точки если тайминго перед HALT не семмитричны 4.
Но тут вроде больше чем 1 точка. Может для инструкции спецефичных не правильно tstate эмулируется?
Рад, что ты всеже над этим думаешь.

**Comment by holub** [comment]
https://hype.retroscene.org/blog/773.html
Набрел, может заинтересует

**Comment by samstyle** [comment]
> Вывод нового цвета бордюра в Пентагоне не выровнен на границу пикселей растрового поля. Поэтому пиксели бордюра слегка смещены по сравнению с пикселями растра. В частности, в конце демо Rage после остановки вращения сегментов на реальном Пентагоне видно, что вертикальная полоска на бордюре слегка смещена влево, по сравнению с полоской на растровом поле

Так это значит, что у меня всё правильно? :)

**Comment by holub** [comment]
Выходит что да, если не брать во внимание, что Rage вообще под эмулем не запускатеся. :D

**Comment by samstyle** [comment]
Rage грешит OUT (#FD),A и не работает на некоторых клонах
А насчет вывода я проверил - у меня вообще сделана запись в порт после команды (т.е в конце 3го такта цикла iowr). и всё равно иногда бордюр сдвинут налево. но не везде.

**Comment by holub** [comment]
Нет желания сделать поддрежку несколькоих клонов Pentagon? Ну хотябы чтобы 2 было...

**Comment by holub** [comment]
1. Есть вот такая картинка. Не могу быть уверенным насколько она правдива.
https://zxuno.com/forum/viewtopic.php?t=122
В эмуле видимый бордюр не в соответсвии с ней рисуется. Другие отсупы.

2. Поговорил с TmK из deMarche. Он сказал Across the Edge тестили на реальном железе, unreal, fuse.
В Xpeccy я вижу на уровне скрина добавляются примерно 2 такта и картинка смещается вправо. (ну или над скрином теряются)

**Comment by holub** [comment]
> 0й такт. Захват прерывания происходит на последнем такте команды предыдущего кадра. Но, чтобы он был захвачен, импульс прерывания должен начаться ещё раньше, на предпоследнем такте команды. Т.е. самым первым тактом кадра, при программном выравнивании на начало кадра, фактически является предпоследний такт предыдущей команды. Поэтому, если такты нового кадра в эмуляторе нумеруются с начала цикла подтверждения прерывания, начиная с нулевого (а это практически стандарт), дальнейшие значения нужно уменьшать на 2.

Это не они?

**Comment by samstyle** [comment]
Последнее, скорее, применимо к медленной памяти и порту FF в ней. Даже если это оно, эффект будет заметен только при изменении экрана прямо под лучом, что маловероятно.
Склоняюсь к проблеме с INT на последнем такте команды.

**Comment by samstyle** [comment]
Захват INT на последнем такте ничего не решил. Это бы устранило захват INT-а, который попал на последний такт, но тогда смещение уже было в 8 точек (4 такта на ещё одну итерацию HALT).
К геометрии экрана пентагона тоже никаких нареканий, она соответствует той, что описана здесь - https://hype.retroscene.org/blog/773.html
Как костыль, можно сделать запись в порт после 1го такта цикла iowr. Сейчас после 2го. Это сдвинет бордюр на 2 точки налево. Других причин, почему имеется расхождение в 1 такт, я пока не вижу.

**Comment by holub** [comment]
Славил очень прикольный эффект. Делаю снапшот, загружаю по F3 и каждый раз имею разную картинкую
![xpeccy_193522_764](https://user-images.githubusercontent.com/58155/118341178-202c7c80-b4ec-11eb-8751-7e0fcbe8f7ae.jpg)
![xpeccy_193549_200](https://user-images.githubusercontent.com/58155/118341179-202c7c80-b4ec-11eb-885d-e6cdd98ca098.jpg)
![xpeccy_193527_519](https://user-images.githubusercontent.com/58155/118341180-20c51300-b4ec-11eb-831f-318b6553530b.jpg)

**Comment by samstyle** [comment]
Со снапшотами вообще мутная тема. Внутри не описано ни положение луча в момент снапшота, ни прошедшие от фронта INT-а такты.
Предполагается, что он сделан на фронте INT-а, а по факту - после команды, по окончанию которой он словился. Из-за этого, если в деме не подстроено так, что это одно и то же время (а это хрен подстроишь), то луч плавает туда-сюда на несколько точек.

**Comment by holub** [comment]
Нет-нет-нет. Эта картинкт через несуолько секунд после восстановления сделаны. Перерывание статичеси сдвигается и экран так и продолжает рендерится до конца.

**Comment by samstyle** [comment]
Я немного не про то. INT может попасть на 1й,2й или 3й такт HALT-а (на 4й, как выяснилось, оно уже не захватится после текущей итерации), который синхронизирует проц с видео. Это уже разница в 6 точек в ту или иную сторону. Сам по себе HALT не значит, что прерывание всегда будет захватываться в одном и том же положении луча. SNA это ну вообще никак не учитывает.

**Comment by holub** [comment]
Мне кажется, что я скачки видел в 10 пикселей. Потещу еще. Но на текущий момент твое объяснение звучит правдопадобно.

**Comment by holub** [comment]
Всеже ссылки вверху, по-моему, объясняют почему в AtE бордюр сдвинут влево.
![Screenshot_20210515-221859~3](https://user-images.githubusercontent.com/58155/118383534-90123400-b5cc-11eb-9a12-bf6046d764da.jpg)
![Screenshot_20210515-221844~3](https://user-images.githubusercontent.com/58155/118383538-930d2480-b5cc-11eb-9b26-9c217b355965.jpg)

**Comment by holub** [comment]
Кстати с одной стороны удобно что после HALT в дебагере устанавливается 0. Но с другой стороны непонятно когда происходит нахлекст из-за некратных тактов, что приводит к "плаванию" изображения. Может в этом случае добавить метку типа "*" в конце счетчика?

**Comment by samstyle** [comment]
Это да, за 0й такт у меня считается такт на котором прерывание захватилось. Более точно можно смотреть по координатам луча справа. Внутри я не могу контролировать точный такт возникновения прерывания, т.к. каждый такт ничего не проверяется. Только в момент iowr/iord/memwr/memrd, перед последним тактом и после команды. Реализация CPU не потактовая.
Предвидя, что "можно определять по отрисованным точкам с момента возникновения прерывания" - нетЪ. Для спектрума и CPU без турбы это сработает (1T = 2 точки), а для всего остального - нет.

**Comment by holub** [comment]
Так ты уже починил AtE. Почему даже не намекнул? Красота с бордюром неимоверная. Спасибо!

**Comment by holub** [comment]
Новый челенж я придумал: https://youtu.be/b-kkzl2foaQ
0:40 - здесь основной картинка "статическая", а в xpeccy морнает.
Либо тактов на цыкл не хватает, либо пепеключение экранов не правильно рендерится.

**Comment by samstyle** [comment]
Отключи нофлик в анриле и снова посмотри этот момент. Так можно и в xpeccy его включить и ничего мерцать не будет.

> Так ты уже починил AtE. Почему даже не намекнул?

https://github.com/samstyle/Xpeccy/issues/116#issuecomment-841646727

**Comment by holub** [comment]
Был бы у меня анрыал на линуксе, я бы хорошим людям мозг не долбил бы.
С noflick работает. Есть небольшие подергивания, но я, всеравно, счастлив вопреки этому.

**Comment by holub** [comment]
И снова здравствуйте! С прыгающим INT после востановления снапшота крайне неприятная штука.
С одной стороны круто что можно потыкавшись в правильное состояние. Но врядли комуто это нужно - для игрух не критично.
Я сохраняю sna из SjAsmPlus и он практически является начальным состоянием как после load "", а бордюр дергается.
Может базовай INT всегда сбрасывать в одно состояние после востановления снэпшота?
