### ISSUE TITLE
Счетчик T-State

### ISSUE THREAD

**Issue by holub** [samstyle/Xpeccy#117]
Можно ли добавить счетчик тактов от поледнего INT в Debug режиме?
Идеально чтобы можно было сбросить счетчик по желанию и считать такты с любого места.

**Comment by samstyle** [comment]
В отладчике над дизасмом есть числа 12/34567
Первое - это счетчик тактов от последнего посещения дебагера. При пошаговой отладке показывает такты каждой команды
Второе - счетчик тактов от последнего INT-а.

**Comment by holub** [comment]
Я сотрел на эти числа, но что-то не нашел закономерности. Вот например:
![image](https://user-images.githubusercontent.com/58155/117146133-e1772380-ad81-11eb-87a3-44e77717a398.png)
Почему второе число не 0?

**Comment by samstyle** [comment]
Потому что пришёл INT -> дождались выхода из HALT -> приняли прерывание -> выполнили процедуру обработки прерывания -> вернулись к точке за HALT. И на всё это кушаются такты CPU

**Comment by holub** [comment]
Ты меня почти убедил. Но процедура прерывантя у меня "пустая" как набежало 871? Пойду поковыряюсь что я там накосячил и закроем тикет потом.

**Comment by holub** [comment]
Мой косяк с HALT был. Но следующий сценарий считаю не логичным:
* В отладчике стою на строчке с "ld hl,0"
* сдвигаю курсор на след строку
* F9
* Первый счетчик показывает 0

Мне кажется, что такты от текущей команды стоило бы добавить.

**Comment by holub** [comment]
F9 будешь фиксить? Если нет, можно закрывать.
Я в принципе F7,F8 могу пользоваться, они предсказуемо работают.

**Comment by samstyle** [comment]
уже закоммитил фикс. когда соберу - уже другой вопрос.

**Comment by holub** [comment]
Замечательно! Собрал из исходников. Работает!

**Comment by holub** [comment]
Если не сложно добавляй номер issue в коммит. Было бы интересно иногда посмотеть где что почем?

**Comment by holub** [comment]
Кстати с одной стороны удобно что после HALT в дебагере устанавливается 0. Но с другой стороны непонятно когда происходит нахлекст из-за некратных тактов, что приводит к "плаванию" изображения. Может в этом случае добавить метку типа "*" в конце счетчика?

**Comment by holub** [comment]
К F9 еще претензии есть минорная. Когда нажимаешь F9 на строке подсвеченной, следуящая остановка - следующая комманда. Немного не удобно цыклы дебажить приходиться по два раза кнопку тыкать.
