### ISSUE TITLE
Эмуляция кемпстона

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#118]
Очень хочется эмуляцию кемпстон-джойстика с клавиатуры, потому что реального джойстика нету. Fuse такое умеет, но в нём дебаггер вообще невменяемый. В том числе новомодного кемпстона, полностью 8-битного, с дополнительными кнопками, а это уже даже Fuse не умеет. Может быть есть возможность расширения настройки маппинга клавиатуры до 31-го порта? Либо с переключением маппинга QAOP на кемпстон по хоткею как в Fuse, либо захардкодить на цифровой блок клавиш по галочке в настройках.

**Comment by samstyle** [comment]
build 20210703
К кастомному мапингу пк-кнопок на zx-кнопки добавлены направления и кнопки джойстика

**Comment by ammehet** [comment]
Сходу не получилось настроить. Делаю так:
```
TAB	C	S
`	C	1
LS	C
RS	C
LC	S
RC	S
N8	JU
N5	JD
N4	JL
N6	JR
N0	JF
```
Табуляции честные, не из пробелов. Пробовал на не-нумпадные назначать (например, на QAOP) – работает. Возможно, это какая-то засада с нумпадом в макоси. Но если мапить на QAOP, то надо хоткей чтобы включать/отключать маппинг на лету (как в том же fuse), иначе пользоваться этим невозможно.

**Comment by samstyle** [comment]
потому что макось не может в nativeScanCode, поэтому отличить нампадовские кнопки от основных просто так не получится, только костылями.

**Comment by ammehet** [comment]
Отличный лайфхак! Работает, спасибо!
