### ISSUE TITLE
deBUGa FDD

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#119]
На закладке FDD очень не хватает символьного представления справа.

![image](https://user-images.githubusercontent.com/47472465/122657458-679dcc80-d16c-11eb-8595-a72e60cb7f41.png)
![image](https://user-images.githubusercontent.com/47472465/122657462-6cfb1700-d16c-11eb-8da7-ea9e3e3e85aa.png)

При этом цветовая подсветка символов справа не обязательна. Создаётся впечатление, что вот это вот как будто специально выпилено

![image](https://user-images.githubusercontent.com/47472465/122657504-b0ee1c00-d16c-11eb-8ad7-7f90a125ce40.png)

На закладке Storage каталоги образов dsk для +3DOS и CP/M не показаны как раз по той причине, что в отличие от того же TR-DOS их место не прибито гвоздями и они сегментированы. И в этом месте закладка FDD показала бы что где и как.
~~hex-viewer без символьного представления отличный оксюморон~~

**Comment by samstyle** [comment]
добавлено
https://github.com/samstyle/Xpeccy/releases/tag/0.6.20210720
