### ISSUE TITLE
Аргументы командной строки

### ISSUE THREAD

**Issue by vito-Z80** [samstyle/Xpeccy#121]
--bp 
Понимает только десятичные и шестнадцатиричные значения, что не очень удобно. Игнорирует метки. (метки могут быть: Main.update)
Так-же дебагер не останавливается даже если указать физический адрес. (подсветка брикпоинта появляется, но дебагер ее игнорит)

0.6.20220219
z80
128k

**Comment by samstyle** [comment]
Опишите шаги, чтобы воспроизвести "дебагер не останавливается даже если указать физический адрес"

**Comment by samstyle** [comment]
Нашёл косячок с отловом fetch на адрес cpu.
Аргументами ком.строки точки ставятся на адрес cpu, не работают по вышеуказаной причине. Метки работают (если загружены до --bp)

**Comment by vito-Z80** [comment]
> Нашёл косячок с отловом fetch на адрес cpu. Аргументами ком.строки точки ставятся на адрес cpu, не работают по вышеуказаной причине. --bp на метки работает (если они были загружены до --bp)

Странно, ссылки для брикпоинта стали работать.
Но да, остановки и открытия дебагера не происходит.
