### ISSUE TITLE
Опрос клавы

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [samstyle/Xpeccy#122]
подробности не раздуплял
но вот в этом гофне не работает опрос space-а
[WarCraft_0_05_alpha.zip](https://github.com/samstyle/Xpeccy/files/8507199/WarCraft_0_05_alpha.zip)
(низя нажать кнопку подтверждения)
в унриале и в zxspin-е оно жметсо 

при том утя в бейсике пробел явно жметсо

**Comment by samstyle** [comment]
А дело не в опросе клавы. Дальше не копал, но похоже что дело в реакции на выбор пункта

**Comment by samstyle** [comment]
Включи у кемпстон-джоя эмуляцию 4 кнопок - и оно заработает. Дело в старших 3 битах из порта 1F. У меня незадействованные биты=1 (в покое читается #E0). Сиё творение хрен кладёт на такой случай и тупо проверяет, что из порта прочиталось #10 (а оно #F0 при установленных старших битах)

**Comment by NEO-SPECTRUMAN** [comment]
ЛОЛ
а де жо идеальный код? :rofl:

**Comment by samstyle** [comment]
А там вообще странные конструкции типа **AND 15:CP 0:JR NZ...** есть

**Comment by NEO-SPECTRUMAN** [comment]
ну в сорце это может выглядеть как
and $0F
cp command_0
и не быть очевидным
