### ISSUE TITLE
Дизасм в буфер обмена

### ISSUE THREAD

**Issue by Bedazzle** [samstyle/Xpeccy#127]
Добавьте пожалуйста копирование выделенного куска дизасма в буфер обмена (Ctrl+C на Windows).

**Comment by Volutar** [comment]
issue вроде как решен в https://github.com/samstyle/Xpeccy/commit/61aa7907d78933c45a16045cb7313511a8843474
 По идее можно закрывать.

**Comment by Bedazzle** [comment]
Спасибо!
