### ISSUE TITLE
Съезжает изображение

### ISSUE THREAD

**Issue by moronizzz** [samstyle/Xpeccy#128]
Привет,

При запуске Xpeccy картинка уезжаешь вправо:

![image](https://github.com/samstyle/Xpeccy/assets/13842146/c19347e4-6c9c-44cd-a723-1cf4d30b30fa)

Если запускать в fullscreen, то всё нормально. Если в настройках video поменять scale, то тоже всё приходит в норму (можно изменить на x1, потом обратно на x2, и изображение будет в порядке).

Собран из последнего коммита

Using SDL ver 2.26.5
Using ZLIB ver 1.2.13
Using Qt ver 5.15.9

**Comment by samstyle** [comment]
Я был уверен, что давно это победил... Можно попробовать немного изменить процент бордюра в настройках, чтобы всё округлялось хорошо.
Кстати, на каком проценте так съезжает? Для отладки.

**Comment by moronizzz** [comment]
О, классно, действительно при некоторых значениях процента бордюра всё нормально с картинкой при запуске.

Не работает: 0%, 5%, 20%, 25%, 30%, 45%, 50%, 55%, 70%, 75%, 80%, 95%, 100%
Работает: 10%, 15%, 35%, 40%, 60%, 65%, 85%, 90%

**Comment by samstyle** [comment]
Просьба проверить на [build 20230713](https://github.com/samstyle/Xpeccy/commit/b572529730247d64cc4827bdc514fa4748518ca7) - я прочекал проценты бордюра от 65 до 75, и с OpenGL и без него. Не съезжало.

**Comment by moronizzz** [comment]
Стало лучше, но теперь оно похоже наоборот в лево клонит, чем меньше процент бордюра, тем ближе к левому краю

![image](https://github.com/samstyle/Xpeccy/assets/13842146/08c8ae88-0a5c-4297-ae73-e9f13ceecffc)

А ещё такое ощущение, как будто интерфейс стал крупнее, но я точно не помню как было. Хотя с моим зрением это даже лучше :)

![image](https://github.com/samstyle/Xpeccy/assets/13842146/a6825ffd-ed7a-4f6e-b68d-5e09ae6f2265)

**Comment by samstyle** [comment]
Интерфейс зависит от выбранной темы Qt. Выбирается где-то в настройках рабочего стола или задаётся параметром --style=NAME при запуске (plastique, cleanlooks итд, это вшитые в Qt стили).
По первому вопросу - на деле левый бордюр меньше правого (примерно 56/72). Просто когда процент большой, это слабо заметно.

**Comment by moronizzz** [comment]
Ясно, значит fixed. Спасибо!
