### ISSUE TITLE
make error:  ‘pnt’ was not declared in this scope

### ISSUE THREAD

**Issue by moronizzz** [samstyle/Xpeccy#131]
> [  0%] Building CXX object CMakeFiles/xpeccy.dir/src/emulwin.cpp.o
/home/user/Xpeccy/src/emulwin.cpp: In member function ‘virtual void MainWin::paintEvent(QPaintEvent*)’:
/home/user/Xpeccy/src/emulwin.cpp:674:9: error: ‘pnt’ was not declared in this scope; did you mean ‘int’?
  674 |         pnt.drawImage(0,0, QImage(comp->debug ? scrimg : bufimg, width(), height(), QImage::Format_RGBA8888));
      |         ^~~
      |         int
make[2]: *** [CMakeFiles/xpeccy.dir/build.make:418: CMakeFiles/xpeccy.dir/src/emulwin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/xpeccy.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by samstyle** [comment]
Fixed
