### ISSUE TITLE
Показывать несколько байт по адресам регистров (Watches)

### ISSUE THREAD

**Issue by Volutar** [samstyle/Xpeccy#16]
Было бы неплохо, если бы по крайней мере содержимое по адресам IX,IY,HL,DE,BC (с текущего набора) было бы отображено, чтобы каждый раз не искать то, что там в соседних адресах. Содержимое в активной памяти, которую видит CPU. Возможно, в виде отдельной вкладки, там где DUMP (CPU/RAM/ROM), отображая пару байт слева и несколько байт справа от памяти, куда указывает регистр. Может где-то в другом месте. В US это очень удобное окошко, но у него там есть один недостаток - он показывает текущий и только следующие байты, но те же индексные часто берутся с отрицательным смещением. Поэтому было бы прекрасным наличие возможности выбирать смещение для отображения, относительно самого адреса регистров (выделяя как-то цветом байт со смещением 0).

В идеале - просто секция watches, в которой можно указывать конкретные адреса, а можно регистры, которые интересны.

**Comment by Volutar** [comment]
Нашёлся Watcher (почему он не открывается из окна отладчика? должна быть кнопка в отладчике)...
Примерно то что надо, но - нет отображения массива (нескольких байт + строки как в dump). Тoлько один Byte+Word - явно недостаточно.

**Comment by samstyle** [comment]
![screenshot_20190109_201508](https://user-images.githubusercontent.com/474306/50916101-53a5fa80-144b-11e9-800e-221936adb25a.png)
Оно?

**Comment by Volutar** [comment]
Да, оно. И хотелось бы чтобы его можно было вызывать из дебаггера, и чтобы в ходе трассировки он работал (а не только в рилтайм).

Вопрос, а можно показывать там массив начинающийся с допустим hl-4? Чтобы как-нибудь цветом выделялась центровая ячейка (+0 которая)?
