### ISSUE TITLE
Метки внутрь комманд, самомодификация кода

### ISSUE THREAD

**Issue by Volutar** [samstyle/Xpeccy#17]
Очень часто код - самомодифицируемый. То есть вида:

**onetime1: ld a,1
          and a
          jr z,label2
          xor a
          ld (onetime+1),a
label2:   ....**

Хотелось бы, чтобы отсылки внутрь инструкций также работали. Либо через смещение в адресации (если метка указывает ровно на саму инструкцию), либо через добавление строки типа:

**ld a,1
onetime: equ $-1
           ...
           ld (onetime),a**

либо

**onetime: equ $+1
           ld a,1
           ...
           ld (onetime),a**

если метка указывает внутрь инструкции.

**Comment by Volutar** [comment]
Тут проблема разбивается на две части:
1. когда метка указывает куда надо, т.е. на начало оператора, но в каких-то местах идёт отсылка на метка+смещение. Это делается относительно просто - метка имеет свою "длину", т.е. сколько байт оператора она охватывает (не только первый), и, соответствующе, может иметь смещение в этом отрезке (от +1 до +3).
2. когда метка указывает внутрь оператора - возможно решение через equ $+смещение (как описано выше), либо через препроцессинг меток, и замена их на вариант (1).

Задача непростая, но если она будет сделана - получится безусловно лучший дизасм, на уровне, а то и выше IDA.

**Comment by samstyle** [comment]
Сложность в том, что дизасм знает только о том, что он показывает. Остальное для него - "куча каких-то байт".
Между делом, метка может указывать не только на код. Это может быть ascii-строка, внутри которой что-то меняется. Это может быть "DW слово", у которого меняют старший байт...

**Comment by Volutar** [comment]
Эти ассемблерные структуры, к сожалению, недоступны. Внутрь структур или строк, с каким-то конкретным известным типом данных (как в том же IDA) - это задача как бы совсем другого уровня, и хранить как-то всю эту кухню, или каждый раз генерировать - гемор.
Логичнее тут просто смотреть в радиусе 3х байт относительно ссылаемого адреса (условно) имеющиеся метки. Брать ближашую в этом радиусе, и на неё ссылаться со сдвигом.
Это как вариант решения (1).

А на вариант (2) - только во время отображения детектить что метка попадает внутрь, и не отображается, и рисовать её отдельной строкой, добавляя строчку с EQU. Проще - ниже, в виде equ $-N.

**Comment by samstyle** [comment]
Что-то проклюнулось
![screenshot_20190114_212748](https://user-images.githubusercontent.com/474306/51132867-8170b200-1844-11e9-959c-66841d88df4c.png)

**Comment by samstyle** [comment]
Метка ищется на 4 байта назад
![screenshot_20190117_190722](https://user-images.githubusercontent.com/474306/51331622-34325180-1a8b-11e9-979d-a17ad3775ea5.png)

**Comment by Volutar** [comment]
Это же чисто визуальный хелпер, тут не будет вреда если сделать "радиус" настраиваемым (и в плюс и в минус).

В моём коде PSM вообще бывают Label-13.

И это касательно операторов типа LD reg,(addr) или LD (addr),reg, но не LD HL,value. Загрузка данных в регистр лично для меня вообще не должна отсылаться к меткам, даже если она +0. Интерпретация каждого значения #FFFF как метки, в случае наличия метки по этому адресу, чревато кучей мест, когда вывод этих значений как метки в 99% случаев будет ошибочным. 

Это безусловно прискорбно, что просто 16разрядные значения EQU, и 16разрядные адреса меток - не имеют никакого признака для того чтобы их отличать.

Хотя, можно было бы принять какое-то соглашения о префиксах, чтобы эту таблицу меток интерпретировать более красиво. Например, если название метки начинается с символа _, то это не адрес. Можно было бы это даже сделать в опциях. Назвать поле например "const label prefix", и если оно задано, интерпретировать все 16разрядные значения, совпадающие со значениями меток с таким префиксом, как метки, даже если это LD DE,#8004.

Примерно такие мысли.

Но вообще выглядит уже зашибенски :) С такими фишками этот "на коленках писанный дебаггер" существенно удобнее всех имеющихся.
