### ISSUE TITLE
Ошибка адресования брякпоинта на "текстовом поле" дампа (брякпоинт ставится на адрес ПОСЛЕ)

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#18]
![ЙА КАРТИНКО](https://i.imgur.com/FXwAV0E.png)

**Comment by samstyle** [comment]
Опиши как воспроизвести. По скриншоту не ясно. Впрочем, по названию тоже...

**Comment by qboneteam** [comment]
Метки же можно ставить и по ПКМ на дампе памяти. Вот ставлю мышку на участок на текстовом отображении дампа (№0008-000F), А брякпоинт ставится на адрес #0010

хотя конечно непонятно куда она и так должна ставится, но явно не на совершенно иной адрес

**Comment by samstyle** [comment]
2 варианта:
- заблокировать левый и правый столбцы
- на обоих сделать установку брыкпоинта на адрес, указанный в левом столбце

**Comment by qboneteam** [comment]
Варианта ТРИ - в правом столбце сделать не все одной строкой, а так же по одному как и слева

**Comment by samstyle** [comment]
пробовал - выглядит очень и очень плохо

**Comment by qboneteam** [comment]
тогда отключи вообще тогда правую. Но хотелось бы чтобы справа всё варно подсвечивался символ соответствующий курсору в левой половине.
И чего слева от текстового отображения много пустого места?

**Comment by Volutar** [comment]
Наверху же чётко написан адрес курсора : Dump : 0008. Но вообще возможность ставить брейкпоинты на целую строку это мисконцепт какой-то.

**Comment by qboneteam** [comment]
Если чётко указан адрес 0х0008 то почему брякпоинт ставится на 0х0010

**Comment by samstyle** [comment]
Всё просто: базовый адрес строки - тот, что указан слева. Текущий адрес рассчитывается как базовый+номер_столбца-1. Но по идее он должен работать только на столбцах 1-8. Самый левый и самый правый столбцы - это побочные эффекты. На левом смещение получается -1, а на правом +8 от базового. Туда и ставятся брыкпоинты

**Comment by samstyle** [comment]
Пока что сделал, чтобы оба столбца ссылались на первый байт. Поставить бряки на область можно, выделив её мышкой.
