### ISSUE TITLE
Перескакивание с "n" на "m" при нажатии на ","

### ISSUE THREAD

**Issue by Volutar** [samstyle/Xpeccy#19]
После запуска и Sinclair research просто набиваешь на клавиатуре клавиши ",,,", затем ext (ss+cs), и снова ",,,", и в итоге то залипает то разлипает cs (то точки то запятые), выводится вот такое:
![image](https://user-images.githubusercontent.com/3478087/50852875-995ab880-13a2-11e9-8d44-39f7812b70f8.png)
Вообще нажимая на клавишу ",<Б" получить символ "." в норме невозможно.

**Comment by samstyle** [comment]
Потыкал в кнопки. Перескок происходит из-за того, что по Ctrl+Shift (CS+SS) меняется раскладка в системе (рус/анг). В английской кнопка (Б) принимается как запятая, (Ю) как точка, в русской почему-то смещение - (Б) как точка, (Ю) как ничего... поищу в таблице, исправлю

**Comment by Volutar** [comment]
Точно, это русский-английский перескок. Вообще, насколько я понимаю, передавать в эмуль коды надо без учёта раскладки, через сканкоды конвертить в zx замыкания.

**Comment by samstyle** [comment]
Раньше пользовался QKeyEvent::nativeScanCode(), но потом оказалось, что он на макоси не реализован, и там клава не работала вообще.
