### ISSUE TITLE
показывалку FPS надобно

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#24]
а то не ясно - тормозит хрессу в данном конкретном окружении, или нет

**Comment by Volutar** [comment]
Подписываюсь под такой надобностью. Просто крепки уж ощущения, что прилично кадров скипаются :(

**Comment by samstyle** [comment]
вам всем надо, сколько полных кадров сэмулировано или сколько их отрисовано? потому как это порой разные числа.

**Comment by Volutar** [comment]
А что, разве может тормозить еще и сэмулированные кадры?
Лично я просто замечаю как регулярно вспышки в длящийся ровно один int, 1/50сек (вывод инфы) просто отсуствует. И подозреваю что не потому что инфы нет, а потому что просто не рисует.
Вот 48 нарисовано на скрине. А 2 оставшихся где? :)

**Comment by qboneteam** [comment]
> А что, разве может тормозить еще и сэмулированные кадры?
> Лично я просто замечаю как регулярно вспышки, длящийся ровно один int, 1/50сек (вывод инфы) просто отсутствуют. И, подозреваю, что не потому что инфы нет, а потому что просто не прорисовывает эмуль.
> Вот 48 нарисовано на скрине. А 2 оставшихся где? :)
> Это, получается, какой-то Framedrops? И это нормально?
Это нормально, ни один эмуль ни под линухом, ни под яблосью, ни под виндой не выдаст тебе честные 50фпс

**Comment by Volutar** [comment]
> Это нормально, ни один эмуль ни под линухом, ни под яблосью, ни под виндой не выдаст тебе честные 50фпс
Может я что-то делаю не так, но всякие версии US, и zx-spin и преснопамятный spectaculator настолько постоянно фреймы не выбрасывал. Гигаскрин смотрелся безо всяких обработок/сглаживаний.

Одно дело нерегулярные фреймы, сглаживаемые за счёт буфера, и совсем другое - безвозвратная их потеря.

**Comment by samstyle** [comment]
Визуальные "пропуски" кадров, скорее всего, случаются из-за разницы в частоте формирования (48.8Гц для пентагона) и частоте их вывода на экран (50Гц). С одной стороны, можно запрашивать перерисовку окна по готовности кадра, и это сгладит эффект, но тогда что-то надо делать с режимом Fast - рисовать каждый кадр уже будет слишком затратно.

**Comment by Volutar** [comment]
вот по этому снапу можно посмотреть насколько фреймы равномерны. [http://volutar.myds.me/gt23.sna](url)
Слева три квадрата - чередуются (gigascreen), справа - через кадр. Из гигаскрина трёхцветового хотя бы один раз каждый должен показываться. У меня какие-то из них по пол секунды отсутствуют. 
Запись с экрана: [http://volutar.myds.me/gs_xp-tst.mp4](url)
