### ISSUE TITLE
WUTcha - просмотр содержимого памяти по МЕТКЕ.

### ISSUE THREAD

**Issue by Volutar** [samstyle/Xpeccy#29]
Просьба сделать возможность добавлять просмотр не только по фактическому шестнадцатеричному адресу и регистру, но и МЕТКЕ (если таблица меток загружена). Сейчас приходится каждый раз лезть в файл с метками и адреса оттуда брать и вбивать адреса.

Сделать можно также как и в строке дизасма - вбил метку, на неё и адресовался, вбил шестнадцаричную строку - перешёл по этому адресу. Метка теоретически может называться c000, но я даже не знаю как дебаггер отреагирует, и перейдёт ли он по адресу c000, или возмёт адрес метки. По логике приоритет за адресом, и нефиг так называть метки :)

Причём, если это значение по метке, то желательно выводить и название метки и её значение (в колонках слева). А колонки слева лучше склеить в такое же как и дебаггере, а не пилить их на отдельные type/page/addr.

**Comment by samstyle** [comment]
Придумалось такое. Можно выбрать метку в качестве источника адреса при добавлении точки наблюдения. При этом для ячейки памяти адрес отображается как RAM:NN:AAAA, просто адрес - просто как AAAA или имя метки, если она указывает на этот адрес.
![screenshot_20190204_192813](https://user-images.githubusercontent.com/474306/52221870-3847d700-28b3-11e9-8838-d66b3a7a6a65.png)

**Comment by Volutar** [comment]
Ну это то, о чём и говорилось в пожелании :)

Кстати, метка так бы было бы хорошо если бы могла вводиться и в поле dump в качестве адреса прыжка (в дизасме ведь можно прыгнуть, и пытаешься в дампе тоже, но обламываешься). А уж елси бы и регистры в поле адреса (и в вотче и в дампе и дизасме) - это было вообще круто :) ну это выходит за рамки этого issue.

**Comment by samstyle** [comment]
> Кстати, метка так бы было бы хорошо если бы могла вводиться и в поле dump в качестве адреса прыжка

Это уже сделано - адрес, метка и значение регистра ( ".HL" ".SP" - по именам регистров в левой колонке отладчика) и для дизасма, и для дампа. Вутчер пока отстаёт.
