### ISSUE TITLE
Перестал отображаться подключенный геймпад

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#31]
Правда работать работает. Но вот не показывается. В связи с чем- а как их менять если подключено несколько?

**Comment by samstyle** [comment]
Используется первый обнаруженый геймпад. Его имя показывается из того, что выдаёт SDL. Пустая строка в настройках ничего не меняет, она только для информации. Хотя, если не показывается - значит, что-то пошло не так

**Comment by samstyle** [comment]
SDL_JoystickName по-разному работает на SDL1.2 и SDL2
