### ISSUE TITLE
Debugger - состояние портов и бордюра. 

### ISSUE THREAD

**Issue by Volutar** [samstyle/Xpeccy#33]
Хотелось бы чтобы в дебаггере, в том же табе, где экран, показывать цвет бордюра текущий (там виден только сам PAPER). Когда луч за кадром, или внутри папера - даже непонятно какой последний out 254 был сделан. 

Также хотелось иметь возможность доступа к состоянию портов, тому же 254, на ввод и вывод (динамик/магнитофон, бордюр), всяким портам TR-DOS, кемпстону/мыши, с возможностью как-то влиять на те, которые завязаны на input.

По 254 порту, из которого считывается состояние клавиатуры, кстати, непонятно как поменять состояния нажатости кнопок. ZX Keyboard, похоже, не передаёт в дебаггер ничего (зафиксировать нажатые кнопки вроде можно по ПКМ, но их состояние считывается только когда дебаггер закрываешь), то есть нельзя сделать так, чтобы они во время действия сканера клавиатуры считывались такими, какие надо в ходе пошаговой отладки. Надо продебажить сканер клавиатуры, джойстик, а не получается.

**Comment by Volutar** [comment]
> У каждого клона свой набор портов 

Клавиатура - абсолютный стандарт. Бордюр - тоже. Кемпстон джойстик можно сказать тоже. Вот абсолютный стандарт хотя бы и показывать. 

> AY генерирует квадратные волны "есть сигнал - нет сигнала", тон-шум миксуется ими. И только потом на это всё накладывается громкость либо канала, либо огибающей.

Понятно. Но тем не менее, это значение заморожено в пошаговом режиме трассировки.

> Предлагаешь для каждого порта в каждом клоне дублировать процедурину считывания?

Нет. Только стандартные порты, описанные в вики (31,254). С 128к пока не было нужды, 7ffd порт почти в каждом эмуляторе есть возможность посмотреть значенияе, включая текущий экран на вывод.

**Comment by samstyle** [comment]
> Клавиатура - абсолютный стандарт. Бордюр - тоже.

Даже среди спектрумов - у профи клава расширена. У АТМ2 в бордюре 16 цветов и свой контроллер клавиатуры. У msx своя клавиатура. У nes и gb клавиатуры нет...

> Понятно. Но тем не менее, это значение заморожено в пошаговом режиме трассировки.

Посмотрим, исправим.

**Comment by Volutar** [comment]
> По бордюру так нормально будет?

Да и меньше бы хватило, 4 пикселя рамки уже было бы достаточно (если что). А так - конечно, более чем нормально :)

> я тут решаю, что нужно, а что нет 🗡

Я к тому, что  экзотики навпихивали много всякой (у меня была профи там обычная клавиатура, расширение которой было просто комбинированием стандартных 40 клавиш). Эмулятор носит название [b]Xpeccy[/b], что намякивает на спектрумовское ядро, потому и логично поддерживать в дебагере ЯДЕРНЫЕ возможности (по портам). Что рисуется AY - отлично, за это большое спасибо.

А GB/NES - ну это уже не спекки, это вообще вне моих интересов.

**Comment by samstyle** [comment]
>что намякивает на спектрумовское ядро

Изначально он эмулировал спектрумы. Но потом эволюционировал и вырос. Ядро там никакое, всё железа присобачивается к нему модулями, эмулятор только управляет связями между ними.

> А GB/NES - ну это уже не спекки, это вообще вне моих интересов.

А мне вот приходится учитывать ВСЁ что там есть, а не только чьи-то интересы

**Comment by Volutar** [comment]
> А мне вот приходится учитывать ВСЁ что там есть, а не только чьи-то интересы

Вроде там все варианты железа конфигурятся. Как и порты. Почему бы эти же конфигурации портов в дебаггере и не обслуживать для вывода? Если он их эмулирует то и нарисовать тем более можно. По логике.

**Comment by samstyle** [comment]
Уровень бипера и входа/выхода мофона
![screenshot_20190128_211607](https://user-images.githubusercontent.com/474306/51857010-3aa1b280-2342-11e9-9a62-8ddc266b2fae.png)

**Comment by Volutar** [comment]
уровень тейпа с реала берётся? просто если это допустим загрузка тап файла экзотического с загрузчиком, он же будет показывать содержимое из тап файла?

**Comment by samstyle** [comment]
> уровень тейпа с микрофона берётся? просто если это допустим загрузка тап файла экзотического с загрузчиком, он же будет показывать содержимое из тап файла?

Нет "содержимого тап файла". Есть очень много пар "длина сигнала + уровень сигнала". При воспроизведении мофон "скользит" по этому массиву и выдаёт уровень сигнала на данный момент, старший бит этого значения попадает в результат чтения с порта FE.
И это не график сигнала по времени, это текущий уровень.

 >что сподвигло меня писать - это трассировка сканера клавиатуры

нашёл где заковырка.

> ну и по поводу не обновления 0/1 всех этих аушных..

уже обновляются

**Comment by samstyle** [comment]
Закоммитил. Проверяй.

**Comment by Volutar** [comment]
Проверю, как только под винду будет сборка. Запустить QT самому не получилось. Буду надеяться что все ок:)

**Comment by samstyle** [comment]
[xpeccy_0.6.20190130_win32.zip](https://github.com/samstyle/Xpeccy/files/2821834/xpeccy_0.6.20190130_win32.zip)

**Comment by Volutar** [comment]
Прошу если зря обращаюсь, но цвет бордюра меняется не после команды out, а через одну. Это нормально?
По логике бордюр меняется не в тот момент когда луч уже нарисовал кусочек, а с началом этого кусочка.

**Comment by samstyle** [comment]
Ога, пнятненько. Причины ясны.
