### ISSUE TITLE
переходы между расширенными (двойными) клавишами - shift отпускается, и вообще клавиатура странно работает

### ISSUE THREAD

**Issue by Volutar** [samstyle/Xpeccy#38]
Замечено, когда жмёшь например влево, а потом резко переходишь на клавишу вправо, на какое-то время shift исчезает (если смотреть на Zx keyboard), и начинают идти цифры 8. 

Дело в том, что в этот небольшой промежуток перехода между нажатыми клавишами, когда они обе нажаты, капс считается зажатым один раз, и при отпускании одной из клавиш - пропадает. Хотя должен оставаться, т.к. вторая клавиша тоже с капсом. В реальности капс восстанавливается, но поздно, цифры уже во всю набираются. Более того, если не отпуская давить капс на клавиатуре и тыкать влево-вправо - капс будет всё равно пропадать!!!
То же самое с Symbol Shift (скобки тоже превращаются в цифры).

**Comment by samstyle** [comment]
Рисую ситуацию: держишь нажатой стрелку влево (CS + 5), потом нажимаешь стрелку вправо ДО ОТПУСКАНИЯ стрелки влево (CS + 8), затем отпускаешь стрелку влево (отпускаются и CS, и 5). Итог - отпущенный CS, но зажатая 8.
Мораль сей басни такова - не насилуй клавиатуру.

**Comment by Volutar** [comment]
Ситуация именно такая. И она должна обслуживаться корректно. С чего это CS отпускается, когда он остается зажатым другой клавишей? На реальном спектруме такое прекрасно работает. Это не насилование клавиатуры - это стандартный "быстрый  набор", когда одну клавишу еще не успеваешь отпустить и нажимаешь вторую.

**Comment by samstyle** [comment]
Ибо есть событие нажатия клавиши и событие отжатия клавиши. По передаваемому коду вычисляется, что должно быть нажато на zx-клавиатуре, а что отжато.
Естественно, такие комбинации плохо влияют на результат.

**Comment by Volutar** [comment]
На спектруме нету события отжатая. Это функционал эмулятора, который клавиши транслирует в двойные. И по какой-то непонятной причине вместо прямой установки значения портов клавиатуры по этим внешним событиям - транслирует это в несуществующее в zx "отпускание" двойных клавиш. В том же US таких проблем изначально не было (да и в куче других эмуляторов).

Почему меня это заботит? Я более 25 лет назад мучился из-за того что в расширенной клавиатуре периодически проскакивали цифры вместо курсора. Из-за того что код шифта появлялся уже в следущий цикл сканирования. Написал свой сканер клавиатуры который это все учитывает (использовал в PSM). Недавно обнаружил что злощасные цифры снова начали вылазить!! Попытался отдебажить - статус клавиш клавиатуры сбрасывался (создавал по этому поводу issue). И вот вчера отлаживая сканер обнаружил что это не из-за него, а из-за эмулятора, проверил в других - цифры не вылазят.

**Comment by samstyle** [comment]
> На спектруме нету события отжатая

Наверное, потому что там контактная матрица, не? Я не про спектрум, я про Qt, который мне отсылает события "клавиша нажата" и "клавиша отжата". И по коду клавиши, передаваемому в эти события, эмулятор меняет матрицу клавиатуры ZX - устанавливает или сбрасывает биты в соотвествующих этой клавише полурядах. Варианты?

**Comment by samstyle** [comment]
Разве что держать список нажатых клавиш, по новому нажатию перестраивать всю матрицу с нуля, а по отжатию - удалять клавишу из этого списка. очередной гемор...

**Comment by Volutar** [comment]
Если так сложно перейти от событийного к сканирующему - может просто считать сколько раз клавиша была нажата, и столько же раз ждать её отпускания чтобы убрать?

**Comment by Volutar** [comment]
В этот же issue добавлю. Я думал что просто часть раскладки клавиш неработают (типа pgup/pgdown), но по Zx keyboard увидел что они загораются как надо.
Проблема в том, что сам ZX их видит совсем не так, а именно:
`  (cs+ss) =>cs+ss+X (а \ корректно cs+ss)
tab (cs+space) => cs+space+I
[  (ss+8) =>ss+8+Y
]  (ss+9) =>ss+8+U
del (cs+9) =>cs+9+P
home (ss+q) =>ss+q+K
end (ss+e) =>ss+e+L
pg up (cs+3) =>cs+3+M
pg down (cs+4) =>cs+4+N

С расширенной клавиатурой странности.
точка почему то в запятую превратилась
делить в вопросительный знак
умножить в 8
минус нормальный, а плюс вообще отсутствует.
[keyb_scan.sna.zip](https://github.com/samstyle/Xpeccy/files/2857840/keyb_scan.sna.zip)

Прикладываю снап для тестирования клавиатуры.

**Comment by samstyle** [comment]
1.Почему так происходит, я уже объяснил.
2.Есть возможность создать свою карту клавиатуры, так что не надо парить мне "как должно быть" - сделай как хочешь
3.Выжал тильду - увидел как переключается курсор [K]<->[E]. Никакого X не проскакивает.

**Comment by Volutar** [comment]
> Есть возможность создать свою карту клавиатуры, так что не надо парить мне "как должно быть" - сделай как хочешь,

Сделал. Не работает. Кастомный map выбирается, но настройки из него игнорируются полностью. 

> Выжал тильду - увидел как переключается курсор [K]<->[E]. Никакого X не проскакивает.

У людей реплицируются эти тройные. Я не просто так приложил .sna. Что-то там явно не так.

**Comment by samstyle** [comment]
> Сделал. Не работает. Кастомный map выбирается, но настройки из него игнорируются полностью (может перевод строки не нравится, или пробелы/табуляции).

Потыкамши в кнопки, выяснил следующее - кеймап не применяется при запуске эмулятора. Если зайти в настройки и выжать ОК - он применится. Формат такой: PCKEY[TAB]ZXKEY1[TAB]ZXKEY2 по одной на строку. ZXKEY2 не обязателен. Названия кнопок тут - https://github.com/samstyle/Xpeccy/blob/master/keymap

**Comment by samstyle** [comment]
А впрочем, кеймапы я всё равно тоже буду переделывать

**Comment by Volutar** [comment]
> Если зайти в настройки и выжать ОК - он применится.
Ок, добился что действует.
Но:
- LS от RS и LC от RC - не отличаются. Qt под виндой видимо не умеет (надо как-то по-особому учить).
- Третий код все равно вылазит. И даже четвёртый.

> Тройные там в принципе невозможны, максимум 2 кнопки может нажаться. Это какие-то побочные эффекты...

Очевидно это побочные эффекты.
[http://volutar.myds.me/xsp_k1.mp4](http://volutar.myds.me/xsp_k1.mp4)
Тут пробегаюсь по всем доп.клавишам. В ZX keyboard загораются 2, а в сканере - в каких-то случаях по 3. Отдельное "O" в тесте при отсутствии клавиш в Zx keyboard - это клавиша insert.
[http://volutar.myds.me/xsp_k2.mp4](http://volutar.myds.me/xsp_k2.mp4)
А вот тут я применил
`	C	1
и вместо двух даже трёх кодов (при базовом это C+S+X, как в первом видео), стало ЧЕТЫРЕ, C+S+X+1.
Ощущение, что он таблицу кодов не переписывает, а дополняет, и в дефолте там на этих доп. клавишах всякие буквы, которые при переназначении никуда не деваются.

**Comment by samstyle** [comment]
Не поленился и запустил твой снапшот
Debian testing: нет лишних нажатий
Win 8.1 под виртуалкой: нет лишних нажатий
Win 8.1 живая: нет лишних нажатий
Есть одна мысля - ты используешь ПРОФИ. И "лишние" кнопки - результат скана его расширенной клавиатуры.

> P.S. также не хватает возможности переназначать цифровую клавиатуру.

В Qt кнопки с цифровой клавиатуры считаются за обычные с модификатором NumLock. Т.е код кнопки Enter должен быть одним и тем же и для основной клавы, и для цифровой.

**Comment by Volutar** [comment]
> Есть одна мысля - ты используешь ПРОФИ. И "лишние" кнопки - результат скана его расширенной клавиатуры.
Да, действительно. Но дело в том, что у меня железный Профи есть, с обычной клавиатурой. И никакой подобной хрени на нём нет. Что за расширенная клавиатура? Почему это никак не конфигурится? Мне, например, никакой расширенный клавиатуры не нужно. Она скорее "ущербная" чем расширенная. Какой от неё прок в _эмуляторе_, где чистой ZX клавиатуры в принципе не может быть, и имеется только XT-шная?

>В Qt кнопки с цифровой клавиатуры считаются за обычные с модификатором NumLock. Т.е код кнопки Enter должен быть одним и тем же и для основной клавы, и для цифровой.

Ясно. Всё бы ничего, но вот клавиша * транслируется в тупую 8, а не ss+8, а + вообще никакого кода не имеет.

**Comment by samstyle** [comment]
> И никакой подобной хрени на нём нет. Что за расширенная клавиатура?

В профи кнопки Delete, Insert, PageUp, PageDown итд выдают свои комбинации клавиш, только с установленным 5 битом при чтении с порта xxFE. Если не захватывать клавиатуру - и эмулятор нажимает свою комбинацию клавиш, и профи. Получается херота.

> но вот клавиша * транслируется в тупую 8, а не ss+8

символ * это Shift+8, но Shift из ряда Shift+цифра исключен, потому что своим нажатием уже вызвал нажатие на zx-клаве CapsShift (по умолчанию)

**Comment by Volutar** [comment]
> В профи кнопки Delete, Insert, PageUp, PageDown итд выдают свои комбинации клавиш, только с установленным 5 битом при чтении с порта xxFE.

Ну, у меня Профи, и клавиш delete/insert/pgup/pgdown нету, обычная матричная 40 символьная клавиатура.

> Если не захватывать клавиатуру - и эмулятор нажимает свою комбинацию клавиш, и профи.

Что значит "не захватывать клавиатуру"? Это вообще легально - эмулировать одновременно обе клавиатуры? Очевидно, что при этом будет херота, если помимо обычной 40клавишной ещё и какая-то кастомная хрень эмулируется. Наверное должен быть какой-то свитч между ними двумя. Ибо к эмулю априорно подключена PC-клавиатура.

> Получается ещё одна херота - CS+SS+L

Если цифровая клава хероту одну генерирует - не проще ли ее вообще "отключить", не транслировать в машину, а забиндить на служебные клавиши эмулятора, как в том же Unreal (или в тот же кемстон, например)? Неужели QT такой тупой, что не умеет хэндлить полноценную PC клаву, с левыми-правыми шифтами, и отдельными кодами для numpad?

**Comment by samstyle** [comment]
> Неужели QT такой тупой, что не умеет хэндлить полноценную PC клаву, с левыми-правыми шифтами, и отдельными кодами для numpad?

QT - Это QuickTime
А про нумпад в Qt я уже сказал - это те же самые основные клавиши с модификатором Qt::NumpadModifier

**Comment by Volutar** [comment]
> QT - Это QuickTime
QT в этом случае это https://ru.wikipedia.org/wiki/Qt набитый в капсе.

>А про нумпад в Qt я уже сказал - это те же самые основные клавиши с модификатором Qt::NumpadModifier

И получается, что этот Qt::NumpadModifier нельзя использовать для более корректной трансляции numpad keys в коды ZX?
Может есть возможность получать не буквы клавиш, переконвертированные по разным раскладкам (кроме рус/анг есть еще и укр и бел и каз и куча других), а сканкоды, чтобы и левый и правый шифт отличать, обрабатывать полноценый numpad, и не зависеть от языковой раскладки? Например через nativeScanCode, где она есть. Ну а если это маке - ну что ж, если ось в плане доступа к сканкодам ущербна, то куда деваться. Благо это не большинство пользователей.

**Comment by samstyle** [comment]
> QT в этом случае это https://ru.wikipedia.org/wiki/Qt набитый в капсе

учим матчасть
QT - QuickTime
Qt - фреймворк, о котором мы говорим

а теперь по теме:
QKeyEvent::nativeScanCode возвращает разные значения в Linux и Windows, в MacOSX вообще не работает. Enum-а для этих значений не нашёл, а это значит что для каждого случая нужна своя новая таблица в где-то 100 элементов (вся клавиатура).
QKeyEvent::key() работает везде, но зависит от модификаторов и раскладки клавиатуры - 1 вернёт Qt::Key_1, Shift+1 сначала вернёт Qt::Shift при нажатии Shift и Qt::Exclam ( ! ) при последующем нажатии 1

**Comment by Volutar** [comment]
> Enum-а для этих значений не нашёл, а это значит что для каждого случая нужна своя новая таблица в где-то 100 элементов (вся клавиатура).

Наверное все же не случая, а платформы. В винде одна, в линуксе другая (наверное). В макосе- либо искать что-то нативное, либо зоопарк вариантов с key().

Вообще, как вариант, дать возможность устанавливать keymap именно в нативных сканкодах (пусть даже без названий). А таблицу с алиасами уже потом добавить. В примере кода выше в макоси key() и берётся.

**Comment by Volutar** [comment]
В новой сборке правые Ctrl/Shift вообще не работают и не биндятся.

**Comment by samstyle** [comment]
Правые специально отрезаны по умолчанию. Плотно проблемой ещё не занимался.

**Comment by Volutar** [comment]
> Их можно забиндить через свой *.map.

К сожалению - не очень. Если бы это сработало, я бы даже комментарий выше не написал.

**Comment by samstyle** [comment]
Проверил - биндятся.
LS	C
LC	S

**Comment by Volutar** [comment]
Левые прекрасно биндятся. Правые не биндятся. 
RS S
RC S

**Comment by samstyle** [comment]
Описька. Проверял с RS/RC. Всё равно работает. Скинь свой *.map

**Comment by Volutar** [comment]
Я ошибся. LS LC и RS - работают, а RC - нет.
Это первое.
А второе - пока не зайдёшь в настройки не нажмёшь ОК - они все не действуют. Вроде проблема давнишняя, я думал её исправили.
[keys.map.zip](https://github.com/samstyle/Xpeccy/files/2890203/keys.map.zip)

**Comment by samstyle** [comment]
Всобачь
`	qDebug() << kent.name << kent.key;
`
Второй строчкой в MainWin::xkey_press в emulwin.cpp и смотри имена и коды нажатых кнопок. Что-то странное происходит, да. Даже если RS+LS сработали, следующее нажатие не срабатывает с первого раза

**Comment by samstyle** [comment]
Усё понятно. Нажатия в окне клавиатуры игнорировали загруженные переопределения. В окне самого эмулятора работало. Это исправил.

**Comment by Volutar** [comment]
Можно было бы микроприложение сбилдить которое бы выводило и логировало кейкод и соответствующий ей нативсканкод. 
У меня кутэ не получилось запустить.

**Comment by samstyle** [comment]
> Можно было бы микроприложение сбилдить которое бы выводило и логировало кейкод и соответствующий ей нативсканкод.

Уже сбилдено. Я же сказал - виртуалка некоторые кнопки не захватывает.

**Comment by Volutar** [comment]
Профи так и остаётся неюзабельным, из-за безальтернативного одновременного "сканирования" сразу двух клавиатур.

**Comment by samstyle** [comment]
Вобщем, как-то выкрутился. Если есть возможность собрать самому и потестить - велкам!

**Comment by Volutar** [comment]
Нет возможности самому собрать, к сожалению :(
Спасибо. Буду ждать бинарничек.

**Comment by Volutar** [comment]
Протестировал.
1. Right Ctrl вообще никак не детектится: перемапливание RC ни к чему не приводит.
2. Одновременные нажатия LS+RS не обнаруживаются.
3. При зажимании LC, затем RS, и отпускании LC - RS остаётся залипшим.
 При зажимании RS, затем LC, и отпускании RS - LC остаётся залипшим.

Залипания вообще с шифтами постоянно происходит :(

Пардон. Могу этот иссуй закрыть и сделать другой на залипания уже.

**Comment by samstyle** [comment]
Для отдельных проблем заводим отдельные темы. Эта была про отпускание нажатых два раза клавиш.
