### ISSUE TITLE
Отображение в Storage не только TRDOS дисков

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#40]
А например и +3

**Comment by samstyle** [comment]
А например формат каталога в студию

**Comment by samstyle** [comment]
Потому как положение и формат каталога варьируется от диска к диску, реализовать не представляется возможным

**Comment by ammehet** [comment]
формат каталога https://www.seasip.info/Cpm/format22.html
готовая либа для DSK https://github.com/lipro/libdsk

**Comment by ammehet** [comment]
а то я с февраля уже научился читать все .dsk, которые понимает +3. могу дать рабочий код листалки конетнта на pure c. вот только куда?

не, ну ок, если никому больше не надо, закрывайте
