### ISSUE TITLE
Некорректно работает загрузка RAW файлов на диск А

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#41]
я плакаю.

**Comment by qboneteam** [comment]
![image](https://user-images.githubusercontent.com/32768894/52520266-ca1b5f80-2c78-11e9-8e72-eedd8c599c5f.png)

**Comment by samstyle** [comment]
Именно на диск А? На другие диски нормально загружается?

**Comment by samstyle** [comment]
С помощью телепатии по скриншоту сразу видно, как должно быть

**Comment by qboneteam** [comment]
ах извольте.... должно быть вот так:
![image](https://user-images.githubusercontent.com/32768894/52520388-77db3e00-2c7a-11e9-9d7b-091046e99c7a.png)

А теперь найдите 256 отличий

**Comment by samstyle** [comment]
Не подтверждено.  Взял screen.scr, создал чистый диск, загрузил в него этот файл, сохранил с диска на винт как screen2.scr - они идентичны. Посмотрел в эмуляторе через LV - увидел первоначальную картинку.
[not_detected.zip](https://github.com/samstyle/Xpeccy/files/2847773/not_detected.zip)

**Comment by qboneteam** [comment]
Несколько раз а разными файлами - одно и тоже! Портится файло!

**Comment by samstyle** [comment]
Дай образ диска, на который загружаешь, и файлы

**Comment by qboneteam** [comment]
Создаю чистый в хрессу

**Comment by samstyle** [comment]
Я создал чистый - всё работает. Дай хотя бы файлы, которые загружаешь

**Comment by qboneteam** [comment]
http://www.worldofspectrum.org/pub/sinclair/screens/load/g/scr/GenghisKhan.scr

**Comment by samstyle** [comment]
Гадом буду, ищи проблему у себя
![screenshot_20190209_163312](https://user-images.githubusercontent.com/474306/52521456-73b61d00-2c88-11e9-9b3f-c46acb067e30.png)

**Comment by qboneteam** [comment]
И не только гадом будешь. Где мне её искать - вот этот файл: 
![image](https://user-images.githubusercontent.com/32768894/52521479-c7286b00-2c88-11e9-9eeb-bd3690de6ae3.png)

После выгрузки бинарника с диска:
![image](https://user-images.githubusercontent.com/32768894/52521507-24242100-2c89-11e9-9fbd-7f230153899d.png)

Значит проблема гдето в нутри хрессу. Потому как выгружает он файл тоже без проблем.

**Comment by samstyle** [comment]
Значит, на дискету внутри эмулятора он записывается без изменений? Если да, закрывай, указанной проблемы не существует. Давай софт, которым смотришь картинку.

**Comment by qboneteam** [comment]
бествью, БГЕ, ЛВ

**Comment by samstyle** [comment]
только что была картинка из BestView, до этого - из LV. И всё нормально

**Comment by qboneteam** [comment]
Я никоим образом ни отрицаю. Потому и говорю - "херота какаято"

**Comment by samstyle** [comment]
Вишь ли, чтобы исправить хероту, мне надо хероту воспроизвести. А она не воспроизводится.

**Comment by qboneteam** [comment]
Это то понятно. Просто где собака то порылась

**Comment by samstyle** [comment]
ДИСКЕТУ МАТЬ ТВОЮ ПОСТАВЬ ДВУХСТОРОННЮЮ

**Comment by qboneteam** [comment]
И нечего не меня КАПС повышать:
![image](https://user-images.githubusercontent.com/32768894/52521651-60f11780-2c8b-11e9-82c2-c008cf51bcaa.png)
КЛОЗЕТ!!!

**Comment by Volutar** [comment]
После обновления версии количество сторон у диска поменялось.  Галка снялась. Думаю каждый с проблемами столкнулся.
