### ISSUE TITLE
И как выяснить что конкретно не так?

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#42]
![image](https://user-images.githubusercontent.com/32768894/52520248-96d8d080-2c78-11e9-9867-f09390d73769.png)

**Comment by samstyle** [comment]
Залезть в настройки профиля test, поменяй железо на нужное

**Comment by qboneteam** [comment]
так конкретно изза чего вылезла эта надпись? Какой РОМфайл он ненашёл?

**Comment by samstyle** [comment]
Не нашёл машину с именем, указанным в конфиге. Если тебя интересуют подробности - BK0011 больше нет. Есть BK0010.

**Comment by qboneteam** [comment]
Ну так и надо конкретно указывать. А то "Поди найди тут ножичек"

**Comment by samstyle** [comment]
PROFILE: TEST. Проблема: HARDWARE
что не ясно?

**Comment by qboneteam** [comment]
Ясно только тому кто это написал.

**Comment by samstyle** [comment]
Нужны картинки со стрелочками, на какую кнопку жать?

**Comment by qboneteam** [comment]
не нужны. Надо прочто указывать чего конкретно и где не найдено. А не просто "АААА. В файле ошибка!!!"
