### ISSUE TITLE
Autofire для геймпада

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#44]
сделать чекбокс в настройках маппинга геймпада чтобы при длительном нажатии на какую либо кнопку включался автофайр - генерация быстрых нажатий этой клавиши.

**Comment by samstyle** [comment]
Вишь ли, я реагирую именно на событие нажатия и отжатия кнопок, я не контролирую длительность их нажатия

**Comment by qboneteam** [comment]
надо чтото придумать. пи этом автофайр должен быть отключаемым и именно на определённые кнопы действовать

**Comment by qboneteam** [comment]
Ну как?

**Comment by samstyle** [comment]
у меня что-то получалось. возможно, что это возможно.

**Comment by samstyle** [comment]
потестил? можно отдавать народу?

**Comment by qboneteam** [comment]
Саш. Чесно, не тестил. Но уверен что у тебя все работает. 

⁣Получить TypeApp для Android ​

На 17 июн. 2019 г., 20:49, в 20:49, samstyle <notifications@github.com> написал:п>потестил? можно отдавать народу?

**Comment by samstyle** [comment]
эт ты зря так уверен XD я, конечно, кнопки понажимал и проверил, но вдруг что не так, и заказчик останется недоволен
