### ISSUE TITLE
AY/YM renderer

### ISSUE THREAD

**Issue by Volutar** [samstyle/Xpeccy#45]
Насколько видел из исходников, никакой передискретизации и КИХ фильтрации звуковых чипов нету. Нельзя ли добавить опциональный рендеринг звуков с КИХ фильтрами? На высоких тонах артефакты дифракционные очень заметны и не очень приятны. Есть вот такая тема с готовой либой: http://hypr.ru/blog/168.html
У Бульбы в zxemul с этим также все хорошо (помимо unreal и кучи других эмуляторов). А аюми вроде считается топом, кому это важно (типа меня) могли бы включать precise sound rendering.

**Comment by samstyle** [comment]
Можно. Добавляй.

**Comment by Volutar** [comment]
Вот пример. [http://volutar.eu5.org/xp-comp.ogg](http://volutar.eu5.org/xp-comp.ogg)
Думаю, что особо не надо гадать чтобы понять какая из половин откуда взята. Части звуков вообще нет, стерео гуляет так что мягко скажем слуховой аппарат неуютно себя чувствует.

**Comment by samstyle** [comment]
Человеческим языком - подстраивать частоту тона чипа, чтобы она была делителем выходной частоты (44100, 22050, 11025 итд)?

**Comment by Volutar** [comment]
К сожалению это невозможно вот так вот просто. Если частоту dsp звуковухи поставить 96кгц, и ту же частоту (96к*16) как аушный (типа 1536000гц), то будет конечно идеально. Но на такой частоте аушки не работают. Передискретизация вносит искажения на высоких частотах. В том же фрагменте у кспекового звука просто отсутствует писк на огибающей, он тупо утерян. И когда в 7-8й октаве звуки питчить и вибратой играться - там низкоуровневые гармоники делают звук вообще неприемлемым.

**Comment by samstyle** [comment]
На. Человеческом. Языке. С формулами, а не с теоретической водой.

**Comment by Volutar** [comment]
Послушай примеры из 3го коммента - это не теория, а вещественный рещультат. Посмотри статью с первого коммента - там подробно описана проблематика с графиками спектральных артефактов. Помимо того ссылка на уже работающий код.

**Comment by samstyle** [comment]
> Послушай примеры из 3го коммента - это не теория, а вещественный результат
Посмотри статью с первого коммента - там подробно описана проблематика с графиками спектральных артефактов

У меня есть исходные данные. У тебя - желание получить из них нужные данные. Для этого с исходными данными нужно провести какие-то операции. С использованием какого-то алгоритма. Описание какого-то алгоритма в студию. Человеческим языком - берём A, с ним проделываем Б чтобы получить В, это нужно чтобы Г.
Копаться в чужом коде, чтобы восстанавливать алгоритм? Неееее

**Comment by Volutar** [comment]
> Копаться в чужом коде, чтобы восстанавливать алгоритм? Неееее


Есть 2 пути. Или даже 3 (но третий нет смысла обсуждать).
1. Изучить теоретическую часть, вникнув в суть (она изложена в статье из первого коммента).
2. Взять готовую функцию рендеринга звука AY/YM из бульбовского эмуля, или из ссылки по статье (алгоритм Аюми), и встроить. Ничего сложного в ней я не увидел. Математики полно (потому как там FIR-фильтр, без которого передискретизация невозможна), и куча этих коэффициентов генералась в MathLab (в том числе и у Бульбы и у SMT для Unreal). Нет никакого смысла пытаться их "проверять". 

Вкратце, повторяю, проблема в том что AY имеет квадратную с частотой дискретизации например 110837.5 периодов, а выводить это надо с частотой 44100. Невозможно "легко" интерполировать одно в другое без порождения в спектре кучи всякого шлака (см рисунки из статьи), в том числе исчезновений частот (как из примера, взята огибающая с периодом 1, то есть 110кгц, звука несущего нет, но есть интерференция с тоном под огибающей, что даёт характерный звук в этой stracker из примера).

**Comment by Volutar** [comment]
Речь про oversampling генерируемого сигнала, и формулу интерполяции до целевой частоты.
В UnrealSpeccy oversampling ratio = 2^6 = 64. То есть фактически "квадратная волна" генерируется для частоты 44100*64, которая через свёртку FIR фильтра со 128 коэффицентами схлопывается до 44100.
https://github.com/darvin/unreal-speccy-portable/blob/master/devices/sound/device_sound.cpp
Но в унреале звук тоже совсем неидеален, хотя и несравненно лучше банального рендеринга на частоте 44100.
Всё-таки предлагаю рассмотреть вот эту версию:
https://github.com/true-grue/ayumi/blob/master/ayumi.c

Её в принципе можно назвать близкой к безупречной (к звучанию реального АУка).
Разумеется, тип интерполяции надо чтобы был опциональным (LQ/HQ, а то мало ли - может железо будет совсем слабое для всех этих oversampling+FIR).

И, да, коэффициенты стерео не должны быть строго 0/50/100 - звучит совсем неестественно (особенно в наушниках). Как правило в большинстве эмуляторов используют формула 10/50/90, со слышимым взаимопроникновением каналов.

**Comment by samstyle** [comment]
Сигнал генерируется постоянно. Обновляется после каждого опкода. В любой момент можно снять громкость с AY. Так что не заливай про оверсамплинг каналов. Ты что-то не то в моём коде вычитал.
ЗЫ: Я знаю, что надо сделать, но я слишком жирный тролль X)

**Comment by qboneteam** [comment]
> Недостаток в той же Stracker слышен на огибающей с делителем 0 (который эквивалентен 1) - http://volutar.eu5.org/frg001.ogg на 53 секунде этот показательный фрагмент, слышно какое-то лишнее прищёлкивание.

Надобно для сравнения обе версии. Ну и там из какого нить музредактора частоты с показаниями где там лишнее щёлкает

**Comment by Volutar** [comment]
> Надобно для сравнения обе версии. Ну и там из какого нить музредактора частоты с показаниями где там лишнее щёлкает

Все что надо - уже предоставлено.

**Comment by Volutar** [comment]
> Сигнал генерируется постоянно. Обновляется после каждого опкода. В любой момент можно снять громкость с AY. Так что не заливай про оверсамплинг каналов.

Если даже генерируется 10^10000 выборок каждую секунду, но в итоговую выборку для DSP звуковухи попадает только 1 из них, это ЭКВИВАЛЕНТНО генерированию 44100 раз в секунду. Они все должны сворачиваться в итоговую выборку.
Так что "заливание про оверсамплинг" тут более чем требуется.

В коде, кстати, я не увидел чтобы делитель 0 был корректно обслуживаемым. Но даже если починить только это - это не нивелирует проблему низкочастотных гармоник.

**Comment by samstyle** [comment]
> частота процессора может быть вообще произвольной (кнопка turbo), в отличие от частоты AY и DSP эмулятора

Так оно и не зависит от частоты проца. Для этого есть абсолютная величина - ВРЕМЯ.

**Comment by Volutar** [comment]
Пример по гармоникам (не по огибающим).
Начало внутриигровой мелодии из [Peter Pack Rat](https://zxart.ee/eng/authors/t/tim-follin2/peter-pack-rat-in-game-ay-1/)

Аудиофрагменты: http://volutar.ey5.org/ppackrat.mp3
1. XSpeccy
2. US
3. Ayumi

В первую очередь слышатся небольшие щелчки из-за 16 ступеней громкости AY - селяви. От этого никуда не деться.
Далее по частотам. В первом - слышатся очевидные артефакты кривой дискретизации в гармониках. Много. Во втором и третьем всё на слух чисто.
Сделал спектрограмму одной из более-менее длинных нот этого фрагмента. И картина следующая:

![image](https://user-images.githubusercontent.com/3478087/53043960-7d6f2a00-34ab-11e9-9b81-124b1faed373.png)

В XSpeccy видно кучу паразитических гармоник дискретизации. В Unreal тоже есть, но совсем маленькие и немногочисленные. В Ayumi - фактически нет никаких паразитических гармоник. Практически идеальный спектр меандра.

**Comment by samstyle** [comment]
Во делать людям нечего...

**Comment by Volutar** [comment]
>> 1. XSpeccy
> Это что?
Это единственный вопрос, который возник по приведённым доводам? Тогда отвечаю - это Xpeccy с опечаткой.

**Comment by samstyle** [comment]
Ты уже 2 день тычешь пальцем в очевидное. Я где-то сказал, что такой проблемы нет?

**Comment by Volutar** [comment]
> Ты уже 2 день тычешь пальцем в очевидное, выпендриваясь терминами и графиками.

Во-первых я не выпендриваюсь графиками и цифрами. Я в первом же посте дал ссылку на полное описание проблемы и одно из её решений. Далее последовали "прокрастенации", "человеческим языком", и "алгоритмы в студию". Попытался уже своим языком объяснить, иллюстрированно. Не понимаю, зачем тут было разводить этот троллинг.

**Comment by samstyle** [comment]
Хочу график на ночном коммите

**Comment by Volutar** [comment]
Бинарник под винду будет нужен.

**Comment by samstyle** [comment]
Нате.
[xpeccy_0.6.20190219_win32.zip](https://github.com/samstyle/Xpeccy/files/2885402/xpeccy_0.6.20190219_win32.zip)

**Comment by Volutar** [comment]
Сверху - было, снизу - стало.
![image](https://user-images.githubusercontent.com/3478087/53120002-a3133680-3572-11e9-9eb6-daa58bb9e5d2.png)

Очевидно что паразитических стало меньше, особенно ниже. Но отражённых (симметричных) гармоник всё равно полно. Я там увидел в коде идёт просто усреднение, безо всякой весовой функции. В идеале это должна быть функция для свёртки типа sinc, но вроде и вот подобное может улучшить ситуацию: 
![image](https://user-images.githubusercontent.com/3478087/53121477-27b38400-3576-11e9-9d3c-67961f4c0521.png)

Но лучше конечно [фильтр Lanzcos](https://en.wikipedia.org/wiki/Lanczos_resampling)

Прошу всё-таки в интерфейс настройки звука добавить выбор частоты и поменять коэффициенты стерео смешивания с полностью дифференцированной на какое-то (например 10%) взаимопроникновение, типа 10+90, 66+66, 90+10, а не 0+100, 66+66, 100+0.

**Comment by samstyle** [comment]
Всё это, кроме стерео, видно только на графике и слышно только эльфам :smile_cat:

**Comment by Volutar** [comment]
Ну я не считаю себя эльфом, но тем не менее все слышу к сожалению очень хорошо, когда начинается трель на 7-8 октаве.

**Comment by Volutar** [comment]
Шумы сейчас играют совсем не так как в других плеерах.
В примере - первый из анрила, второй - из xpeccy. 
[http://volutar.myds.me/xp-nois.mp3](http://volutar.myds.me/xp-nois.mp3)

**Comment by Volutar** [comment]
Шумы все еще кривые.

**Comment by Volutar** [comment]
Шумы всё еще кривые.

**Comment by Volutar** [comment]
Похоже, всё исправлено. Незначительные гармоники на ультразвуковых делителях не сильно ломают звук. Теперь не хуже чем в любых других эмуляторах.

**Comment by samstyle** [comment]
Уот это да, уот это да, уот это нифига себе. И всего-то полтора года прошло XD
