### ISSUE TITLE
Сборку под Haiku OS надобно

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#46]
Очень преочень

**Comment by samstyle** [comment]
Собери

**Comment by threedeyes** [comment]
Вот вам - http://haikuware.ru/files/screenshots/Xpeccy.png

**Comment by samstyle** [comment]
А мне для этого пришлось бы ещё одну виртуалку заводить. Хайку ведь не зачрутишь в дебиане?

**Comment by threedeyes** [comment]
Только виртуалку или на реальное железо. Ну или с кроссскомпиляцией возиться.
Вообщем вроде всё победил - сейчас всё отлично работает. В ближайшие дни напишу рецепт для автоматической сборки пакета - будет в Haiku-репозитарии ещё и Xpeccy.
