### ISSUE TITLE
[Windows], Left/Right Shift/Ctrl отрабатывают вместе и залипают.

### ISSUE THREAD

**Issue by Volutar** [samstyle/Xpeccy#48]
Наблюдается неприятные моменты:
1. Не отрабатывает одновременное нажатие на левую и правую мод.клавишу, т.е. left ctrl одновременно с right ctrl не видится. То же самое и с shift. 
2. Зажав LS затем RS, и отпускаем LS, при этом залипшим остается RS. И в обратной последовательности так же. Если после залипания одной нажать на одну клавишу с другой стороны (например при залипшем LS нажать RS), то она также залипает. При выходе в дебаг залипы уходят.
3. Даже если не перемапливать LS/RS/LC/RC, то залипы всё равно случаются с нажатиями на LS+LC. Причём, при зажатом LC, потыкивание на LS не даёт залипы, а при зажатом LS потыкивание на LC даёт залип, но не первый раз - со второго потыкивания с вероятностью где-то в 50%. Выход в дебагер этот "счётчик" сбрасывает. т.е. после выхода в дебагер одиночный LC+LS никогда не залипает. Сброс в дебагере работает ТОЛЬКО если ZX Keyboard не включен, а если он включен то залипания остаются после входа в дебаггер. И более того - все залипы прекрасно отображаются на ней.

**Comment by samstyle** [comment]
Нашёл в интернетах код от правого контрола. Просьба проверить хотя бы его.

**Comment by Volutar** [comment]
Теперь зажав один из контролов, второй игнорится первый раз, и только со 2го нажатия отрабатывает. Если отпустить 1ю после второй, то 2я залипает.
То есть нормально работает только если держать левый контрол, и дважды ткнуть на правый, и потом отпустить левый. И наоборот.

**Comment by Volutar** [comment]
Патч для исправления
[diff_kbd.patch.zip](https://github.com/samstyle/Xpeccy/files/6007849/diff_kbd.patch.zip)

**Comment by Volutar** [comment]
Исправленно коммитом:
https://github.com/samstyle/Xpeccy/commit/59f988a9cdb57107358b90f547a68b2a3a70b5b6
