### ISSUE TITLE
[DEBUG] Отображение страниц в дизасме/дампе

### ISSUE THREAD

**Issue by Volutar** [samstyle/Xpeccy#49]
Когда переключаешься с CPU на RAM/ROM в дизасме - все время отображается RAM:00, вне зависимости от того, какая страница выбрана (RAM/ROM отображается, но номер страницы всегда 00). В дампе вообще никогда RAM:00 даже нет, всегда только 4х-циферный адрес.
![image](https://user-images.githubusercontent.com/3478087/53688269-41697e00-3d63-11e9-9d82-e43974c2c7ba.png)

**Comment by samstyle** [comment]
В дизасме отображение номера починил, а в столбец дампа полное название не влезает, надо растягивать саму таблицу...

**Comment by Volutar** [comment]
Там такие промежутки между хексами, что растягивать таблицу не обязательно - достаточно уменьшить padding на 1-2 пикселя.
