### ISSUE TITLE
[MacOS] Keymap

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#50]
Использую сборку 0.6.20190301, на предыдущих такое же поведение.

Включение KeyMap с использованием любого .map файла, даже с пустой секцией [Keymap file] приводит к стабильно одному и тому же результату. Клавиша с цифрой 1 перестаёт работать в любых комбинациях (shift, ctrl, command, alt), в том числе и на дополнительной клавиатуре. Только выбор в настройках KeyMap: none возвращает ожидаемое поведение.

Также не мапится ctrl, ни левый, ни правый. Такое ощущение, что эта клавиша вообще не обрабатывается.

**UPD** научили посмотреть, что там на самом деле происходит через ZX Keyboard. Выяснилось много интересного. Например, нажатие 1 при включенном кеймапе выглядит как одновременное нажатие 2 и 3:
![image](https://user-images.githubusercontent.com/47472465/53694142-5c67dc80-3dbb-11e9-8c84-0612e55e5808.png)
Также обнаружено, что ctrl действительно вообще не участвует в процессе, а LC совершенно замечательно мапится, только вместо ctrl на command. А RC просто в никуда.

**Comment by samstyle** [comment]
У меня нет маковской клавиатуры, поэтому проверять не могу...
В файле *.map вообще не должно быть секций. просто строки формата
PCKEY[tab]ZXKey1[tab]ZXKey2

**Comment by ammehet** [comment]
Ух! А я просто взял keymap.example и добавил в него свои комбинации. Без секций единица отлично работает! Но кто ж знал? Надо как-то в keymap.example закомментировать эти секции, а то вот встречаются такие буквально понимающие, как я, например =)

Спасибо, этот вопрос снят!
