### ISSUE TITLE
установка режима окна через консоль при запуске

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#52]
Хотелось бы иметь возможность при запуске указывать ресайз окна/фуллскрин. Возможно ноуфлик и пропорции
-x1, x2, x3,x4,full - это к размеру окна
также другими параметром ноуфлик и пропорции

**Comment by samstyle** [comment]
-s | --size N = режим увеличения (от 1  до 4)
--fullscreen N = полноэкранный режим (0 или 1)
-r | --ratio N = сохранять ли пропорции в полноэкранном режиме (0 или 1)
-n | --noflick N = установить нофлик от 0 до 100%
