### ISSUE TITLE
макось версия не работает под mohave (10.14.4)

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#53]
![image](https://user-images.githubusercontent.com/32768894/57449305-33a10f00-7264-11e9-8af2-4de6414260a1.png)

**Comment by qboneteam** [comment]
![image](https://user-images.githubusercontent.com/32768894/57449611-13258480-7265-11e9-8dcf-8236a2299e3f.png)

вот что в консоли

**Comment by samstyle** [comment]
не могу тестировать в отличной от эль капитано (10.11.6) версии

**Comment by kolnogorov** [comment]
Я могу как-то помочь протестировать?

**Comment by qboneteam** [comment]
Ну если только собирать билды будешь на более старших версиях.

**Comment by kolnogorov** [comment]
Помогите кто-нибудь запустить Xpeccy на Мохаве. Что только ни пробовал, не запускается и всё тут.

**Comment by kolnogorov** [comment]
На Каталине тоже :(

**Comment by kolnogorov** [comment]
Внезапно, я разобрался сам, в чём дело.
У меня стоял SDL2, а нужен был SDL1.
Качаем его вот отсюда: https://www.libsdl.org/release/SDL-1.2.15.dmg - и кидаем папку SDL.framework в /Library/Frameworks. И всё работает!
