### ISSUE TITLE
numpad-insert перестал работать как insert

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#55]
после перехода на нэйтивскан перестал работать нумлоковый инсерт ((( и теперь невозможно с клавиш перейти в режЫм "ФАСТ"

**Comment by samstyle** [comment]
insert и numpad-insert теперь разные кнопки. фаст на инсерте никуда не делся

**Comment by qboneteam** [comment]
Просто у кого нет инсёрта - оченно страдают

**Comment by samstyle** [comment]
Пока что знаю целого одного такого человека
