### ISSUE TITLE
Надобно хэлп по хоткам в дебагере встроить в эмуль

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#56]
а то старый стал - забывать начал....

**Comment by ammehet** [comment]
> а то старый стал - забывать начал....

В выпадающих менюшках справа от названия подсказку хоткея сдедать было бы уместно.

**Comment by samstyle** [comment]
Хоткеи, в т.ч. и хоткеи дебугера, вынесены в настройки. Это удовлетворило?

**Comment by ammehet** [comment]
Да, супер! Спасибо!
