### ISSUE TITLE
нужен special mode

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#57]
для использования хрессу для расчётов и подготовки всяческих табличек.
Например включается по опкоду rst 0
и дальше команды типа save/load в винду/линух, переключение страничек и выход из этого режима и эмуля соответственно

**Comment by samstyle** [comment]
не нужен

**Comment by qboneteam** [comment]
Бля буду! Нужен!

⁣Получить TypeApp для Android ​

На 4 июл. 2019 г., 21:29, в 21:29, samstyle <notifications@github.com> написал:п>не нужен
