### ISSUE TITLE
Заголовок диска при работе с SCL

### ISSUE THREAD

**Issue by Volutar** [samstyle/Xpeccy#60]
Как известно, SCL образы не содержат какого-либо заголовка. И нигде не регламинтируется что нужно какое-то название туда подставлять. Но лучше всё-таки хотя бы подставлять в название пробелы (это дефолтовый label диска), а не нолики, как сейчас.

Просто размышления: если пытаться подставлять туда название файла образа, то это может создать проблемы если название файла выходит за рамки ASCII (но в идеале какое-то название быть должно, и лучше уж это будут пробелы, как в других эмуляторах).

**Comment by samstyle** [comment]
Исправлено. 9 байт по смещению #ea и 8 по смещению #f5 в служебном секторе заполняются пробелами.

**Comment by Volutar** [comment]
Благодарю!
