### ISSUE TITLE
Надобно! Быстрый переход на адрес в дампе

### ISSUE THREAD

**Issue by qboneteam** [samstyle/Xpeccy#64]
Сейчас при кликанье мышой на адрес - происходит переход на этот адрес в дизасме. Считаю необходимым донести информацию о крайней степени необходимости реализации перехода по адресу в дампе при кликанье например с шифтом, контролом

**Comment by samstyle** [comment]
Ты вот не поверишь, но если кликнуть второй кнопкой мыши - произойдёт чудо!
