### ISSUE TITLE
config.conf: пара неприятных пустяков

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#65]
1) Переменная lastdir в секции [GENERAL] корректно сохраняется, но при запуске всегда ресетится на $HOME (проверял только в макоси).
2) Хочется сохранение положения окна. Вроде и не сложно при запуске перетянуть из середины экрана в привычное место, но таки сабж.

**Comment by samstyle** [comment]
я это только что переделывал :)
в следующем коммите lastdir будет корректно сохраняться для каждого профиля отдельно

**Comment by samstyle** [comment]
Сохранение позиции окна тоже сделано

**Comment by ammehet** [comment]
Шикарно! Спасибо!

**Comment by ammehet** [comment]
Сохранение позиции работает таки кривовато. В макоси при каждом новом запуске сползает вниз примерно на высоту заголовка окна.

**Comment by samstyle** [comment]
Есть такое дело. Перепоймал, переисправил. Почему-то QMoveEvent в позиции выдаёт Y=24 в самом верху экрана. Не учитывает заголовок?

**Comment by ammehet** [comment]
Не знаю тонкостей. Может из-за того, что в макоси сверху экрана менюбар гвоздями прибит примерно такой же высоты. А может оно координаты клиентской части окна возвращает без учёта границ и заголовков. С Qt я дел не имел, но в винде встречал такое где-то, типа, чтобы не заморачиваться с темами оформления.

**Comment by samstyle** [comment]
https://github.com/samstyle/Xpeccy/releases/tag/0.6.20191227

**Comment by ammehet** [comment]
Всё красиво, но ВНЕЗАПНО кнопки F1-F12 перестали работать...

**Comment by samstyle** [comment]
Да блин... Короче, пока что так - в ~/.config/samstyle/xpeccy/config.conf в секции [KEYS] прописать их руками для каждой функции.

**Comment by ammehet** [comment]
Эмм... А что за функции? В моём конфиге такой секции вообще нету.

**Comment by samstyle** [comment]
тогда так - открой опции из меню (пкм - options) и выжми ok. тогда секция должна сохраниться

**Comment by samstyle** [comment]
PS: а всё равно не работает. ок, будем исправлять

**Comment by samstyle** [comment]
Заменил dmg в релизе
https://github.com/samstyle/Xpeccy/releases/tag/0.6.20191227
Хотя, у меня в virtalbox-е он не хочет эмулить - выдаёт 0 фпс и ничего не делает. Если и на реальном маке это будет так, буду копать дальше

**Comment by ammehet** [comment]
Работает!
