### ISSUE TITLE
Переназначение хоткеев

### ISSUE THREAD

**Issue by kolnogorov** [samstyle/Xpeccy#69]
Помимо хелпа по хоткеям было бы хорошо сделать возможно задавать свои хоткеи, любым способом, хоть через текстовый конфиг.
Дело в том, что например у меня на F1 системно повешены разные вещи, поэтому использовать эту кнопку не представляется возможным.

**Comment by samstyle** [comment]
Пока в зачаточном состоянии - в конце главного конфига config.conf появилась секция KEYS, там можно назначить функциям, которые висят на F1-F12 другие кнопки (для начала одиночные, без модификаторов).

**Comment by samstyle** [comment]
Сделано в билде 20200310. Хоткеи относятся только к главному окну, отладчик на подходе.
![Screenshot_20200310_231429](https://user-images.githubusercontent.com/474306/76356324-cef08e00-6326-11ea-8e97-fd01057dcc0d.png)

**Comment by samstyle** [comment]
И даже так
![Screenshot_20200311_234502](https://user-images.githubusercontent.com/474306/76462243-653db600-63f2-11ea-8222-114df265e3c0.png)
