### ISSUE TITLE
(OS X, Ubuntu) Баги с отображением элементов интерфейса в отладчике

### ISSUE THREAD

**Issue by alexanderk23** [samstyle/Xpeccy#7]
На OS X окно дебаггера выглядит вот как-то так (сборка из master):

![2017-03-08 17 35 22](https://cloud.githubusercontent.com/assets/1713462/23710987/977189ba-042f-11e7-8f4e-29c5fea1dedf.png)

Весна, даже виджеты лезут друг на друга ;)
На дефолтных Ubuntu 14.04 и 16.04 примерно та же история с наползанием виджетов, но дамп там отображается.

**Comment by samstyle** [comment]
Ужасненько. :) Растяну окно в следующем срезе. Кстати, в OSX сейчас работает клавиатура в плане передачи кнопок в спектрум?

**Comment by alexanderk23** [comment]
Тут после сборки внезапно оказалось, что вместо ROM-ов почему-то мусор, поэтому кроме снапшотов ничего не запустить. Причём именно в ОС Х, под убунтой сейчас собралось и работает нормально.
![2017-03-08 23 51 09](https://cloud.githubusercontent.com/assets/1713462/23723427/321c329c-045a-11e7-88b9-d87397775cc3.png)

**Comment by alexanderk23** [comment]
Клавиатура, кажется, не заработала.

**Comment by samstyle** [comment]
Для OSX пока что не инициализируются пути, где лежат файлы конфигов (src/xcore/config.cpp, функция initPaths), потому как я понятия не имею, где они по канону должны лежать. Если бы был какой-нибудь хакинтош, который мне в виртуалбокс установился, я бы быстрее это уладил.

**Comment by alexanderk23** [comment]
В теории, это ~/Library/Preferences/<APPNAME>. В Qt5 вроде как есть [инструменты](http://doc.qt.io/qt-5/qstandardpaths.html#details) для получения стандартных путей в зависимости от системы, в Qt4 сходу не нашёл. Хакинтош никогда не пробовал ставить, так что даже не знаю. Но, если вдруг чего, я всегда готов собрать и потестить )

**Comment by alexanderk23** [comment]
Почитал ещё и сам запутался. Класс QSettings в Qt при использовании формата .ini (а не нативного для оси) и на Linux и на OS X кладёт конфиги просто в ~/.config/%ORGNAME%/%APPNAME%, как сейчас. Так что может быть даже правильнее оставить всё как есть.

**Comment by samstyle** [comment]
Над клавиатурой я работаю. Сейчас бы проверить, с каких мест пытаются читаться rom-ы и почему не читаются.

**Comment by alexanderk23** [comment]
Окей. Вечером попробую посмотреть, что происходит, по результатам отпишусь.

**Comment by alexanderk23** [comment]
В общем, с путями всё нормально, а вот при чтении ромов в profile.cpp std::ifstream.readsome() возвращает 0 и ничего не читает. С заменой на read() работает.

**Comment by samstyle** [comment]
Попробуй build 20170309. Клавиатуру, ромы и отладчик. Отладчик можно растянуть в ширину, чтобы всё влезало

**Comment by alexanderk23** [comment]
Собрал, в src/libxpeccy/filetypes/raw.c надо поменять __APPLE на __APPLE__.
Ромы читаются, окно отладчика:
![2017-03-09 23 32 24](https://cloud.githubusercontent.com/assets/1713462/23769535/c4aaa74e-0520-11e7-8b3d-76ac7b1fbcae.png)
Клавиатура заработала! Ура! )

В убунте пока всё так же:
![2017-03-09 23-33-49](https://cloud.githubusercontent.com/assets/1713462/23769691/4263b3e2-0521-11e7-9801-1b0c54f99592.png)

**Comment by alexanderk23** [comment]
Ещё про одну штуку я забыл: окно приложения после запуска надо вручную поднимать на передний план (я влепил после `show()` у себя `raise()` и `activateWindow()`), само не вылезает, стесняется.

**Comment by samstyle** [comment]
romsize используется только для gameboy. хотя, и его, наверное, можно отрезать. остальное учту.
попробую перекомпоновать окно отладчика. надо как-то проверять его под разным окружением и темами оформления.

**Comment by alexanderk23** [comment]
Спасибо!
Кажется, можно практически начинать забывать про анрил из-под вайна )
