### ISSUE TITLE
Save TAP

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#71]
Проблема с сохранением на ленту. Ну, то есть, во «внутреннюю» тапку оно пишет, в настройках видно новые блоки. А саму «внутреннюю» тапку при этом сохранить никак нельзя. По F9 только диски, и в интерфейсе кнопок никаких нет. И «сохранить как...» тоже нету.

Да, можно отдельный блок из TAP сохранить в TRD, затем сохранить TRD, затем из TRD перекинуть обратно в TAP. Но это как-то...

И было бы вообще шикарно, если бы крыжык «Fast loading» также умел «Fast saving».
И «Autoplay» при записи.

**Comment by samstyle** [comment]
Отвалилось. Раньше можно было сохранять в tap записанное через стандартную процедурину. Проверю.

**Comment by samstyle** [comment]
Уточнение.
1. При записи на ленту после каждого блока в консоль выдаётся сообщение вида "size: X   AAA BBB CCC DDD...". Если можно, покажи его.
2. Только что проверил. SAVE "11" CODE 0,256. F5 (rec). Any key. *wait*. F5 (stop). F2, там есть пункт с *.tap, указываем имя name.tap (расширение обязательно, по нему определяется тип файла), и всё проходит успешно.

**Comment by ammehet** [comment]
1)
```
Using SDL ver 1.2.15
Using ZLIB ver 1.2.5
Using Qt ver 5.3.2
SDL audio device opening...success: 44100 1764 (32784 / 32784)
Joystick not opened
size: 6
        2157    667     735     856     1710    945
size: 6
        2157    667     735     1711    852     945
```
2) F2 работает, спасибо! Сразу не заметил, там выпадающий список кривой какой-то, скроллить надо
![Screen Shot 2019-12-09 at 19 32 02](https://user-images.githubusercontent.com/47472465/70454199-1c0c5c00-1abb-11ea-8e47-c310f944df4f.png)

**Comment by samstyle** [comment]
Кривость интерфейса зависит от декорации окон. Конкретно этот список похож на GTK-шный.

**Comment by ammehet** [comment]
Но у меня макось, откуда GTK? Да и недавно было что-то про принудительное включение оформления в макоси. Проверил сейчас ещё в разных местах xpeccy выпадающие списки. В файловых диалогах, где есть выбор типа файла, везде так – один крайний не помещается (сверху или снизу). Да и сам диалог выглядит нестандартно, на винду похоже.
![image](https://user-images.githubusercontent.com/47472465/70457859-f9ca0c80-1ac1-11ea-8549-6df41ca72fb6.png)
Если тип файла не выбирается, то стандартный макосьный диалог выходит.

**Comment by samstyle** [comment]
можешь попробовать запустить xpeccy --style. будет нативный стиль, но от этого будет не легче :)

**Comment by ammehet** [comment]
Ну да, выпадающие списки стали аккуратные, зато дебаггер обратно разьехался. Собственно, из-за чего и затевались эти принудительные стили.
![image](https://user-images.githubusercontent.com/47472465/70494363-17c45b00-1b1c-11ea-8586-336afc96f274.png)
GTK-шному пары точек высоты не хватает, чтобы скролл убрать.

**Comment by ammehet** [comment]
А что «Fast saving»? Сложнааа?

**Comment by samstyle** [comment]
если просто перехватывать адрес в пзу, как с загрузкой, то не сложно. но пока только для спектрума не +2/+3, там другие адреса

**Comment by ammehet** [comment]
Странно. Через `#04C2` на +2/+3e работает. Даже сообщение про «Start tape» в одном и том же месте лежит, хотя и текст отличается. Или какие-то другие адреса имеются ввиду?

Кстати, на +3e быстрая загрузка работает.

**Comment by samstyle** [comment]
У меня быстрая загрузка не работала на +2/+3. всё зависит от пзу.
Быстрая запись и автостарт при записи на ленту сделаны. Когда докопаю выявленные попутно проблемы с мофоном - соберу.

**Comment by ammehet** [comment]
Турбо-читалка тапок отвалилась. xpeccy_0.6.20191214_x86_64.dmg, пробовал на конфигурациях Pentagon/Scorpion/+2A/+3. Мгновенно `R Tape loading error, 0:1`. Без турбы читает.

**Comment by samstyle** [comment]
Ясно, опять на следующий блок автоматом не переходит. Выловил.

**Comment by ammehet** [comment]
xpeccy_0.6.20191219_x86_64.dmg всё ок. Спасибо!

**Comment by samstyle** [comment]
На самом деле нет. Загрузка последнего блока без турбы приводит к tape loading error. Сижу, исправляю...

**Comment by ammehet** [comment]
Странно. Попробовал самодельную тапку на +2 со включенной неработающей турбой и на пентагоне с выключенной, всё грузится до конца без ошибок.

Другое дело, что когда читать что-то по заданному имени, типа `LOAD "lr-levels" CODE`, то он пытается прочитать первый попавшийся заголовок и на этом останавливается, пока его носом не ткнёшь в нужное место тапки. Ожидаемое поведение в таком случае «пони бегают по кругу» до тех пор пока не наткнётся на нужное, либо не остановят.

[level-editor.tap.zip](https://github.com/samstyle/Xpeccy/files/3986713/level-editor.tap.zip)

**Comment by samstyle** [comment]
поиск блока по имени - ещё более zx-специфичная штука, чем автостарт и турбо-загрузка. Тем более, данные на ленте хранятся не в виде байтов, а в виде пар "длина - амплитуда" для каждой половины волны.

**Comment by ammehet** [comment]
С данными на ленте понятно. Вопрос в остановке ленты после успешного считывания не того заголовка. Читалка продолжает ждать следующий заголовок, игнорируя блоки данных, а лента остановилась. Тут скорее «ложное срабатывание» автостопа, критерии которого мне неизвестны.

**Comment by samstyle** [comment]
нашёл где собакен порылся. это не ложное срабатываение автостопа, это не переход к следующему блоку при несовпадении размера. На самом деле он постоянно пытается загрузить один и тот же блок, и безуспешно, потому что это не заголовок. Нашёл, исправил. Ждём-с коммита-сборки

**Comment by samstyle** [comment]
Проверяем-с: https://github.com/samstyle/Xpeccy/releases/tag/0.6.20191222

**Comment by ammehet** [comment]
Шикарно работает с турбой и без неё!
