### ISSUE TITLE
Question about contributions and different HW (ZX Next)

### ISSUE THREAD

**Issue by ped7g** [samstyle/Xpeccy#73]
Hello, I took a very quick look on your emulator so far (just couple of minutes of toying with it), and I really like most of it.

What are your plan with development? Are you considering adding also ZX Spectrum Next emulation (which is unfortunately quite a lot extended compared to regular ZX128, but you already have machines like Evo TSConfig and other ones, which are far from trivial ZX extensions too)?

Would you eventually accept pull requests with changes (even larger changes, like new machine), or do you prefer to work alone on the emulator and know all the code in detail?

Do you mind communicating in English and discuss this?

(I'm asking like this, because I tried for example to help with ZX Next (TBBlue) emulation in ZEsarUX, and the author did try to use my help, but in the end Cesar prefers to work alone and in his own way, not accepting pull requests any more ... which is fair decision, but unlucky for me)

Thanks for your opinions and answers.

**Comment by samstyle** [comment]
I need a good documentation on ZXNext - memory managment, ROMs, IO ports description and so on - and a bunch of examples (snapshots, videos, screenshots etc) to understand how it works. And then i will try. I can't promise when and how good it will be :) ...
Current goal is to fix multiple bugs and improve emulation of soviet BK0010 and C64.

**Comment by ped7g** [comment]
And what is your view of bigger pull requests from other people, do you think you can work that extra bit to review+comment them until you would feel comfortable to accept them?

--------

I can help with hunting down documentation and basic explanation, also I'm co-author of the test suite focusing on emulator authors: https://github.com/MrKWatkins/ZXSpectrumNextTests

(be aware the Next itself is currently still moving target, so those tests often need refresh and update. There are still new features added a bugs fixed, although it's expected to calm down in following month after the cased units will be shipped to project backers).

**Comment by samstyle** [comment]
I don't like 'not-my' code in my projects. Better way is give documentation to me and answer on my questions about it.
Maybe, it's better to wait for 'stable' version of ZXNext?
