### ISSUE TITLE
ATM Turbo 2+ рендер текстового режима

### ISSUE THREAD

**Issue by ukmsz** [samstyle/Xpeccy#76]
Привет! Спасибо за эмулятор! Похоже это единственный юзабельный эмулятор ATM Turbo2+ на маке. И судя по всему имеется какая-то проблема с отображением атрибутов текстового режима, вот скрин из ванильного биоса bios_1_07_13.rom. На xbios тоже видна проблема - если зайти в настройки экран должен быть равномерно залит синим фоном. Размер бордюра настроен по разному в эмуляторах, поэтому окна не совпадают. На дефолтных настройках эмулятора кстати обрезается крайний левый столбик в текстовом режиме, фиксится увеличением размера бордюра 50%->100%.
<img width="1407" alt="Снимок экрана 2020-04-19 в 13 19 00" src="https://user-images.githubusercontent.com/43314076/79685656-18e06400-8243-11ea-8817-8771a259dc5e.png">

**Comment by samstyle** [comment]
Благодарствуем-с. Действительно, неверно рассчитывался индекс цвета для paper-а. Изменение закоммичено, но сборку ещё придётся подождать.
![Screenshot_20200419_151907](https://user-images.githubusercontent.com/474306/79687605-28ff4000-8251-11ea-99e4-7d4a0954e6c4.png)

**Comment by samstyle** [comment]
https://github.com/samstyle/Xpeccy/releases/tag/0.6.20200428
