### ISSUE TITLE
сборка под MacOS

### ISSUE THREAD

**Issue by RandomAmbersky** [samstyle/Xpeccy#8]
Пожалуйста в app под MacOS добавь все необходимые либы для запуска, для этого там есть утилита macdeployqt:

~/Qt/5.8/clang_64/bin/macdeployqt Xpeccy.app -dmg

Без либ сборка сегфолтит.. Запускаю из dmg отсюда - http://zx-pk.ru/threads/9479-xpeccy.html

**Comment by samstyle** [comment]
Проблемка... Qt библиотеки добавляются, но SDL в упор не видится

**Comment by RandomAmbersky** [comment]
https://habrahabr.ru/post/220961/ - может вот это как-то поможет?

**Comment by samstyle** [comment]
https://yadi.sk/d/wEFX5t4I3GoGNS - попробуй этот. я долго учил cmake собирать сначала в *.app, а потом из него делать *.dmg. Пока что не понял только как иконку добавить

**Comment by RandomAmbersky** [comment]
О чудо!

![2017-04-09 20 43 33](https://cloud.githubusercontent.com/assets/436951/24839539/4436f1b4-1d65-11e7-83ff-e82a5e60df2d.png)

**Comment by RandomAmbersky** [comment]
В релизе https://github.com/samstyle/Xpeccy/releases/tag/0.6.20200120 под MacOS 10.15.3 программа не запускается по причине отсутствия SDL-библиотек в образе (может и раньше не запускалось, столкнулся только сейчас на машине где не установлены SDL глобально).

Фиксить следующим образом (возможно потребуется поставить пакет разработчика xcode):

- качаем дистриб http://www.libsdl.org/download-1.2.php и монитруем его
- копируем папку SDL.framework в **xpeccy.app/Contents/Framework**, туда где лежат фреймворки от Qt
- запускаем в папке xpeccy.app/Contents/MacOS команду **install_name_tool -change @rpath/SDL.framework/Versions/A/SDL @executable_path/../Frameworks/SDL.framework/Versions/A/SDL ./xpeccy**

**Comment by samstyle** [comment]
Да, оно и раньше не запускалось без установленного SDL1.2. Я тупо не знал правильного способа добавить либы в *.app. Для Qt нашёлся macdeployqt. Команду добавлю в секцию cmake, отвечающую за сбор образа.

**Comment by samstyle** [comment]
тэк-с, я кажется вкурил, что к чему. Но остаются ещё несколько системных либ - они всегда есть и критично ли это?

/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

**Comment by RandomAmbersky** [comment]
Думаю, их можно оставить как есть. Спасибо.
