### ISSUE TITLE
no sound under ubuntu

### ISSUE THREAD

**Issue by d00rsfan** [samstyle/Xpeccy#82]
Hello!
Ubuntu 20.04,
sudo apt install cmake libsdl2-dev
git clone https://github.com/samstyle/Xpeccy.git && 
cd ~/Xpeccy/ && mkdir build && cd build/ && cmake .. && sudo make install
xpeccy
no sound (run test: 10 BEEP 1,1 20 GO TO 10).
Setting -> Sound -> Volume Levels -- no xpeccy here
BTW the same issue also with another emulator, zesarux, 
Who know how to fix this issue?

**Comment by samstyle** [comment]
try this:
sudo apt-get install libasound2 libasound2-dev

**Comment by d00rsfan** [comment]
либы установлены :( кроме эмуляторов спектрума, всё остальное играет, даже фубар2к через вайн играет.
sudo apt-get install libasound2 libasound2-dev
...
libasound2 is already the newest version (1.2.2-2.1).
libasound2-dev is already the newest version (1.2.2-2.1).
$ xpeccy 
Using SDL ver 2.0.10
Using ZLIB ver 1.2.11
Using Qt ver 5.12.8
Joystick not opened
NULL device opening...

**Comment by samstyle** [comment]
> NULL device opening
Options -> Sound -> Output: выбрать SDL. И тоже в консоли посмотреть, открывает ли и какую ошибку пишет

**Comment by d00rsfan** [comment]
Спасибо, виноват, не досмотрел :(
