### ISSUE TITLE
Цвета в дебаггере

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#83]
Это нормально такой кислотный цвет окошка со спектрум-экраном в дебаггере? Такое только в ts-conf, в остальных конфигурациях всё ок

![image](https://user-images.githubusercontent.com/47472465/86823409-81e2b580-c095-11ea-939f-99ec283742d1.png)

**Comment by samstyle** [comment]
Причина в следующем - все без-палитровые спектрумы используют цвета 00..0F из палитры в 256 (цвета задаются в эмуляторе), и экран рисуется этими же цветами. TSConf считает, что спектрумовские цвета - с индексами F0...FF, а цвета 00..0F использует под свои нужды (если вообще использует)

**Comment by samstyle** [comment]
исправлено
https://github.com/samstyle/Xpeccy/releases/tag/0.6.20200731

**Comment by ammehet** [comment]
Вообще шикарно! Спасибо!
