### ISSUE TITLE
mimic tv screen

### ISSUE THREAD

**Issue by Ygarr** [samstyle/Xpeccy#84]
Please add mimic tv screen stripes like as it is in attach
![74599258-93480880-5087-11ea-9f9a-ed433eebf931](https://user-images.githubusercontent.com/14309871/91924239-de9bce80-ecda-11ea-8017-8bf83a292843.gif)

**Comment by a7mag3ddon** [comment]
They are called scanlines and i would also like to see those implemented.

**Comment by samstyle** [comment]
i will try. something like this: after drawing frame picture i will lower bright for each odd line, but it will be looking strange for zoom x1

**Comment by a7mag3ddon** [comment]
I tried a 3rd party program called Reshade which i have used before on emulators for scanlines but couldnt get it to work.

**Comment by Volutar** [comment]
There is a possibility to use OGL + custom made shader.
Like:
![image](https://user-images.githubusercontent.com/3478087/108053682-8d587f00-706f-11eb-9cc7-c42f76a43c1b.png)

But is it really necessary to have all these crappy TV output glitches, like dot crawling, pixel shimmer, ray divergence, signal instability, and so on?

**Comment by a7mag3ddon** [comment]
Just scanlines would be ok, no need shimmer  dot crawling etc.. it would just give people a choice to add it ? I have a JS Speccy 128, Spectrum next and they just dont look right without faint scanlines adding. I guess its just how i remember mine back in 1985 :)

**Comment by samstyle** [comment]
Just scanlines is already there. Options->Video->TV scanlines. You can set hotkey to switch it on/off - Options->Xpeccy->Keys, Switch scanlines

**Comment by a7mag3ddon** [comment]
![xspeccyvideo](https://user-images.githubusercontent.com/20628018/108061661-8a9a6180-7050-11eb-8f50-feb6c7906ce7.PNG)

I dont have that option, have i gone scanlines blind? :)

**Comment by samstyle** [comment]
Which build is this?

**Comment by a7mag3ddon** [comment]
5th oct 2020

0.6.20201005

**Comment by samstyle** [comment]
i see... https://github.com/samstyle/Xpeccy/releases
latest is 0.6.20201229

**Comment by a7mag3ddon** [comment]
Thanks i now have scanlines options but can hardly see them, can you make them look more the top post here?

**Comment by samstyle** [comment]
ok

**Comment by Volutar** [comment]
I wonder where is this GIF from first post was taken from? It has clear TV artifact along with pretty stable line structure (low intensity, medium and high,from top to bottom).

**Comment by Ygarr** [comment]
I don`t remember, i was just looking for example like in Fuse emulator. This example was the first one found 
 BTW I made similar request for "ZX-Poly" emulator  java-based. But his implementation hurts eyes.
 Well, how did he do - this is his vision.

**Comment by samstyle** [comment]
Now it looks like this (scale x4). But looks awful on fullscreen.
![Screenshot_20210216_232736](https://user-images.githubusercontent.com/474306/108118038-d24fd600-70ae-11eb-8a13-2951b5177d1f.gif)

**Comment by Volutar** [comment]
Latest version (since 2021-02-19) Xpeccy supports GLSL shaders, mimicking tv lines/aperture (like screen from my previous message).

**Comment by Volutar** [comment]
Shaders in Xpeccy are text files with sections started with "vertex:" and "fragment:"
Apart from texture itself 3 parameters are passed to shader:
* rubyInputSize - initial resolution before scaling
* rubyTextureSize - size of texture (always as above)
* rubyOutputSize - application resolution
Stored in /config/shaders/*
This folder is reread with pressing Setup (F1), and can be chosen within "Video" tab.
Also they can be switched with context menu.
There's a hotkey of shader reload (if you decide to play with const values in script, and see how it comes).

Xpeccy shader examples (built mainly with lottes script, and another one):
[xpeccy-shaders.zip](https://github.com/samstyle/Xpeccy/files/6014545/xpeccy-shaders.zip)

**Comment by samstyle** [comment]
> though the list of shades is not renewed
Опять у тебя всё не как у людей. при вызове быстрого меню список файлов обновляется.

**Comment by a7mag3ddon** [comment]
Wow absolutely beautiful! i love what youve done in such a short time, ive only tested 3 but they are amazing!

**Comment by samstyle** [comment]
solved in OpenGL version by shaders
