### ISSUE TITLE
How to load floppy disk

### ISSUE THREAD

**Issue by Ygarr** [samstyle/Xpeccy#85]
Trouble with loading floppy disk(.SCL or .DSK format) cannot also find docs. Is it implemented? tap tzx are ok

**Comment by samstyle** [comment]
First step - set disk interface in settings. BetaDisk for russian clones, +3DOS for Spectrum+3
![Screenshot_20200718_151423](https://user-images.githubusercontent.com/474306/87852323-916dc400-c909-11ea-9918-143be2e5fa52.png)
Second step - press F3 and load disk image

**Comment by Ygarr** [comment]
After repeating this nothing happens, seems no ROM after selecting e.g. Scorpion machine invitation string of 48K machine...

**Comment by samstyle** [comment]
There is ROMs pack - https://yadi.sk/d/YHkQUZLrwEaMEg
Unpack it to config/roms folder, then press a button with a bulb (see screenshot). After that romset must contain one file scorpion.rom (if scorpion selected). Set 'reset to basic128'... and that's all, must be working
![Screenshot_20200720_151754](https://user-images.githubusercontent.com/474306/87936888-56e86080-ca9c-11ea-89d8-74246e9671d5.png)

**Comment by Ygarr** [comment]
Seems all`s working now. Gratitude
