### ISSUE TITLE
Сохранение путей

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#86]
1) При установленной галочке Restore media диски восстанавливаются после перезапуска, а кассета нет.
2) Если кассету затолкать в эмулятор не руками, а (мак)осью через «открыть с помощью», то это новое расположение образа нигде не запоминается.
3) В дебаггере после перезапуска эмулятора тоже пути для дампов и меток не сохраняются, каждый раз начинает из-под себя. Хотя, если _руками_ загрузить кассету/диск, то уже с той папки начинает, но после перезапуска эмулятора снова забывает. Пункт 2) сюда тоже относится. Хочется, чтобы он сохранял _своё_ состояние. А при загрузке нового образа (как сейчас и работает) уже начинал с новой папки.

**Comment by samstyle** [comment]
1,2 покопаюсь
3.запоминание последнего каталога работает только на открытие-сохранение, которое висит на F2/F3. Открытие-сохранение дампа из дебагера делается через стандартный QFileDialog::openFile. Вообще, чтобы не открывать дампы и метки руками, рекомендую посмотреть на ключи при запуске ( -a, -b, -f, -l )

**Comment by ammehet** [comment]
О, про ключи я даже не подумал, надо юзать.
Есть подозрение, что если починить 2), чтобы драг-энд-дроп или «открыть с помощью» срабатывали как F3, то 3) просто самоликвидируется.

**Comment by ammehet** [comment]
А есть возможность в уже запущенный эмуль метки подпихнуть снаружи, по типу как образ подпихивается?

**Comment by samstyle** [comment]
Чтоб прям взять и дропнуть в окно - нет, потому что дропнутый файл считается чем-то, что можно открыть по F3 в эмуле (т.е снапшоты/образы ленты-диска/итд). Метки это все-таки немного не то.

**Comment by samstyle** [comment]
Вот, раскопал багулину. Пути ленты сохраняются, через "открыть с помощью" тоже. Просьба проверить.
[xpeccy_0.6.20200806_x86_64.dmg.zip](https://github.com/samstyle/Xpeccy/files/5042812/xpeccy_0.6.20200806_x86_64.dmg.zip)

**Comment by ammehet** [comment]
Да, всё сохраняется. Только дебаггер не врубается в изменившийся путь при драг-энд-дропе для полного счастья. Хотя, не уверен, надо ли оно – забытый ключик -l превосходно работает.
Спасибо!

**Comment by samstyle** [comment]
Драг-н-дропа меток нет, и из-за внутренних особенностей сейчас сделать это невозможно без основательного перетряхивания. Так что только с -l
