### ISSUE TITLE
Resize deBUGa window

### ISSUE THREAD

**Issue by Bedazzle** [samstyle/Xpeccy#90]
Окошко дебага можно расширить по горизонтали.
По вертикали почему-то нельзя. Особенно мешает на вертикальном мониторе, когда есть много места, а кода видно мало.
Windows.

**Comment by samstyle** [comment]
Наконец-то добрался до этого. В коммите 20210306 окошко можно растягивать по вертикали, число строк дизасма и дампа динамически меняется

**Comment by samstyle** [comment]
меньше 913x657 становиться ни в какую не хочет. И дело даже не в регистрах слева. Ведётся расследование...

**Comment by lvd2** [comment]
Вот с таким вот "патчем"
```
diff --git a/ui/debuger.ui b/ui/debuger.ui
index 4269d34..55ea545 100644
--- a/ui/debuger.ui
+++ b/ui/debuger.ui
@@ -13,6 +13,7 @@
   <property name="font">
    <font>
     <family>DejaVu Sans Mono</family>
+    <pointSize>9</pointSize>
    </font>
   </property>
   <property name="windowTitle">
@@ -925,6 +926,7 @@
        <property name="font">
         <font>
          <family>DejaVu Sans Mono</family>
+         <pointSize>9</pointSize>
         </font>
        </property>
        <property name="contextMenuPolicy">
```
удалось чуть поджать окошко дебага, но тем не менее всё равно оно целиком не лезет.
![Screenshot at 2021-03-10 16-51-50](https://user-images.githubusercontent.com/6805375/110639749-1ec79680-81c1-11eb-8ccd-5fcb8b29f1e4.png)

**Comment by samstyle** [comment]
У formLayout можно уменьшить verticalSpacing:
    <layout class="QFormLayout" name="formLayout">
       <property name="verticalSpacing">
        <number>2</number>
       </property>

но больше сжиматься не даёт правая часть

**Comment by Bedazzle** [comment]
> 
> 
> Наконец-то добрался до этого. В коммите 20210306 окошко можно растягивать по вертикали, число строк дизасма и дампа динамически меняется

Супер, под Peppermint работает.
Как можно скомпилить под винду?

**Comment by samstyle** [comment]
> Как можно скомпилить под винду?

В выходные постараюсь всё собрать

**Comment by Bedazzle** [comment]
> 
> 
> > Как можно скомпилить под винду?
> 
> В выходные постараюсь всё собрать

Я сам попробую, просто не знаю, с чего начать.
Что-то шаманить нужно?

**Comment by samstyle** [comment]
qt.io
libsdl.org
cmake.org
а потом надо шаманить с QtCreator-ом (он идёт в составе Qt)

**Comment by Bedazzle** [comment]
> qt.io
> libsdl.org
> cmake.org
> а потом надо шаманить с QtCreator-ом (он идёт в составе Qt)

QtCreator я для виндопитонов использую.
Под линухом Xpeccy собрать удалось, и запустилось. Куда дальше копать, чтобы скомпилить экзешник для винды?

**Comment by samstyle** [comment]
настраивать QtCreator. Указать ему, где cmake, добавить путь к либам/заголовкам SDL. Скачать исходники xpeccy, открыть CMakeLists.txt в креаторе и смотреть, на что он ругается. Когда cmake успешно отработает - считай 70% дела сделано, можно настраивать параметры проекта и жать кнопку "скомпилировать"
