### ISSUE TITLE
MSX2 (alfa)

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#91]
Раньше (0.6.20201026) работало, а сейчас понадобилось, но что-то пошло не так.
Причины поясняет: Assertion failed: (0), function brkOut, file /Users/sam/src/xpeccy/src/libxpeccy/hardware/common.c, line 15.
Там ещё много, но всё бесполезное.

**Comment by samstyle** [comment]
Раз выпало по assert, то это дебажная сборка (сам собирал?). И раз выпало - проц пытается делать out в порт, про который эмуль не знает - какая строка перед assertion failed (должно быть "out xxxx,xx и ещё куча всего"

**Comment by ammehet** [comment]
Не, у меня самостоятельно не получается собирать. Видимо, тулчейн другой и от этого результат разный. Всегда жду авторский релиз. И в этот раз что-то поломалось, потому что даже не стартует, а сразу заваливается. Не поленился прошлый релиз проверить – 0.6.20201026 не заваливается. А 0.6.20201122 некрасиво падает, как раз на потребовавшемся MSX2

**Comment by samstyle** [comment]
тогда вдвойне странно, почему вываливается по assert. причину вышеописанного я нашёл.

**Comment by ammehet** [comment]
Значит таки была причина. Хорошо, что нашлось. Спасибо за лучший эмуль, буду ждать новый релиз

**Comment by samstyle** [comment]
check: https://github.com/samstyle/Xpeccy/releases/tag/0.6.20201202

**Comment by ammehet** [comment]
Да, больше не падает. Спасибо!
