### ISSUE TITLE
UI: Автоматический выбор ROMs

### ISSUE THREAD

**Issue by holub** [samstyle/Xpeccy#92]
Теперь:
* выбрал Machine
* нажал "лампочку"

Хотелось бы:
* выбрал Mаchine
* все ромы подставилсь
* кастомизировал ROMs, если надо

**Comment by samstyle** [comment]
Людям уже лень кнопку нажать. Полная автоматизация не нужна и противоречит концепции конструктора.
Кастомизация ромов и так есть. Это называется Romset парой строчек ниже Machine - можно создавать и настраивать какие угодно наборы.

**Comment by holub** [comment]
Ну с RomSet тоже получиться два клика вместо одного.
Но Вам виднее как должен выглядеть продукт
