### ISSUE TITLE
Grab mouse

### ISSUE THREAD

**Issue by ammehet** [samstyle/Xpeccy#93]
А можно не захватывать мышку при клике на окно, когда в текущей машине нету kempston mouse?

**Comment by samstyle** [comment]
Можно

**Comment by samstyle** [comment]
Это тоже бы проверить на реальных маках. В теории уже есть

**Comment by ammehet** [comment]
Если хакинтош считать реальным маком, то да, мышка перестала захватываться, когда отключена в настройке текущей машины. Спасибо!

**Comment by samstyle** [comment]
Ну, у меня вообще хакинтош в виртуалке, его там крючит и колбасит во все стороны. Хотя бы на реальной машине работает - уже гуд.
